### ISSUE TITLE
Can't recover wallet if .grin/wallet_data/ folder don't exists already

### ISSUE THREAD

**Issue by hogwash89** [mimblewimble/grin-wallet#10]
Can't recover from phase if I firstly not init the wallet, then I can recover my existing wallet from phrase.
Recover command can't create wallet_data folder.

If I create wallet_data folder manually then recover works, creates wallet.seed file there.

20190307 21:58:36.353 ERROR grin_refwallet::command - Error recovering seed - IO error
Wallet command failed: IO error

**Comment by garyyu** [comment]
thanks for report, this can be improved in the future version :-)

**Comment by mcdallas** [comment]
What you are looking for is the `grin wallet init -r <yourphrasehere>` command

**Comment by yeastplume** [comment]
as @mcdallas says, closing
