### ISSUE TITLE
Got error '400 Bad Request with data Body' when sending via owner API 

### ISSUE THREAD

**Issue by rlinxy** [mimblewimble/grin-wallet#100]
Hi, I am trying to send some grins by using the wallet API. Just following this instruction:
 GitHub

[mimblewimble/docs](https://github.com/mimblewimble/docs/wiki/Wallet-API-Guide#wallet-sending-via-api)

When I reached step 2, and executed the command

> data=cat issue_send_tx-1.json; curl -0 -XPOST -u grin:XXXXXXXXXXXXXXX http://127.0.0.1:3420/v1/wallet/owner/issue_send_tx -d “$data” 2>/dev/null

I got this error

> Client Callback Error: Posting transaction slate (is recipient listening?): Request error: Wrong response code: 400 Bad Request with data Body

I am sure the ‘recipient’ was listening, this is a Bitmesh grin deposit address.

The json file is as below:

> {
> “amount”: 210000000,
> “minimum_confirmations”: 10,
> “method”: “http”,
> “dest”: “https://grin.bitmesh.com/o58oRLtbPSKLLvcnnSWyUD7dab 1”,
> “max_outputs”: 500,
> “num_change_outputs”: 1,
> “selection_strategy_is_use_all”: true
> }

What am I doing wrong? Please help. Thanks

**Comment by rlinxy** [comment]
added 
“target_slate_version”:0
to json file, seems it works

**Comment by wwaayyaa** [comment]
The way @rlinxy said is feasible
