### ISSUE TITLE
Potential error in docstring for v2 API

### ISSUE THREAD

**Issue by michaeldzjap** [mimblewimble/grin-wallet#102]
Shouldn't the command part of [this](https://github.com/mimblewimble/grin-wallet/blob/b9e3a90e1210df84d9a3c4fc2eee9de02f9116a4/api/src/owner_rpc.rs#L28) line read as `grin-wallet owner_api`? I've tried both and only the latter one actually seems to open port 3420 and expose the endpoints.

**Comment by yeastplume** [comment]
Thanks, yes the docstring is wrong, it should be `grin-wallet owner_api` to run the owner api, as you say. Will fix
