### ISSUE TITLE
An error occurred "Wallet command failed: LibWallet Error: Can't Deserialize slate"

### ISSUE THREAD

**Issue by llgoer** [mimblewimble/grin-wallet#108]
Send by http `./grin-wallet send -m http -d http://x.x.x.x:3415 76`
An error occurred
```
Password: 
Wallet command failed: LibWallet Error: Can't Deserialize slate
```
I just in 'chain_type = "UserTesting"'

send by file success.

I use latest beta version of grin wallet.

grin:v1.1.0-beta.2
grin wallet : v1.1.0-beta.3

**Comment by vandabbin** [comment]
I am using grin:v1.1.0 and grin-wallet:v1.1.0 and getting the same 
`Wallet command failed: LibWallet Error: Can't Deserialize slate`
when attempting to send to an https address. works fine when saved to file

**Comment by Incrediblez7** [comment]
Please reopen it. I'm having the same issue. 
`grin-wallet send -m http -d https://grin.hotbit.io/353758 1.64`
The exact same error appeared: `Wallet command failed: LibWallet Error: Can't Deserialize slate`

Grin: 1.1.0
Grin-wallet: 1.1.0

**Comment by kargakis** [comment]
Issue reopened at https://github.com/mimblewimble/grin-wallet/issues/145

**Comment by pro2pop** [comment]
hi! the same  trouble 
 grin-wallet send -m http -d "https://grin.hotbit.io/315748" 10
Password:
Wallet command failed: LibWallet Error: Can't Deserialize slate
node 1.1.1-beta.1
wallet 1.1.0

**Comment by taoteh1221** [comment]
Same issue in v1.1.0. Additionally, when trying the optional method of:
``
grin-wallet send -d "transaction.tx" -m file XX.XX
``
although the CLI response seems ok:
``
Command 'send' completed successfully
``
Poloniex rejects the file:
``
Invalid File
``

**Comment by jaspervdm** [comment]
The are most likely running pre v1.1 wallet, so use `-v 0` flag when sending.

**Comment by taoteh1221** [comment]
Thanks for the idea @jaspervdm , however even this was rejected by poloneix as "invalid file":
``
grin-wallet send -d "transaction1.tx" -v 0 -m file 1.00
``
Maybe I should try -v 1?

**Comment by taoteh1221** [comment]
Looks like you HD seed in v1.1.0 isn't backwards compatible with v1.0.0 as well (seems that way for me at least, idk). I'm presuming funds are stuck until v1.1.0 is fixed.

**Comment by taoteh1221** [comment]
No go with -v 1 either, just so you know. Will wait for the patched version.

**Comment by jaspervdm** [comment]
If it doesnt work with `-v 0` flag, it's a problem on Poloniex's end.

> Looks like your HD seed in v1.1.0 isn't backwards compatible with v1.0.0 as well 

What do you mean? Nothing regarding key derivation changed

**Comment by taoteh1221** [comment]
@jaspervdm Maybe when I entered the recovery seed on the v1.0.X version it didn't rescan the chain...in fact, I don't recall it doing so. The UX was better when I reinstalled / resynced v1.1.0, I was alerted to use recovery mode. All good, thanks for your time. I appreciate it. I guess poloniex has some wallet maintenance to do.
