### ISSUE TITLE
Invoice finalize isn't working

### ISSUE THREAD

**Issue by mcdallas** [mimblewimble/grin-wallet#111]
on current master

>  $ fw invoice -d /tmp/inv2.tx 0.6
> 20190519 16:12:23.175 INFO grin_util::logger - log4rs is initialized, file level: Debug, stdout level: Debug, min. level: Debug
> 20190519 16:12:23.175 INFO grin_wallet - Using wallet configuration file at /Users/mike/.grin/floo/grin-wallet.toml
> 20190519 16:12:23.175 INFO grin_wallet - This is Grin Wallet version 1.1.0-beta.3 (git v1.1.0-beta.3-1-g94aee6f), built for x86_64-apple-darwin by rustc 1.33.0 (2aa4c46cf 2019-02-28).
> 20190519 16:12:23.175 DEBUG grin_wallet - Built with profile "release", features "".
> 20190519 16:12:23.175 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /Users/mike/.grin/floo/wallet_data/wallet.seed
> 20190519 16:12:23.176 DEBUG grin_store::lmdb - DB Mapsize for /Users/mike/.grin/floo/wallet_data/db/lmdb is 549755813888
> 20190519 16:12:23.176 INFO grin_wallet_impls - Using LMDB Backend for wallet
> 20190519 16:12:23.176 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /Users/mike/.grin/floo/wallet_data/wallet.seed
> 20190519 16:12:23.622 DEBUG grin_core::libtx::build - Building output: 600000000, Commitment(096d636ffe52a024940a608f6815cd4cc931bc7164843eb13e4052a823c9b2c68c)
> Command 'invoice' completed successfully

>  $fw pay -i /tmp/inv2.tx -d /tmp/paid2.tx     
> 20190519 16:13:01.425 INFO grin_util::logger - log4rs is initialized, file level: Debug, stdout level: Debug, min. level: Debug
> 20190519 16:13:01.426 INFO grin_wallet - Using wallet configuration file at /Users/mike/.grin/floo/grin-wallet.toml
> 20190519 16:13:01.426 INFO grin_wallet - This is Grin Wallet version 1.1.0-beta.3 (git v1.1.0-beta.3-1-g94aee6f), built for x86_64-apple-darwin by rustc 1.33.0 (2aa4c46cf 2019-02-28).
> 20190519 16:13:01.426 DEBUG grin_wallet - Built with profile "release", features "".
> 
> This command will pay the amount specified in the invoice using your wallet's funds.
> After you confirm, the following will occur:
> 
> * 0.600000000 of your wallet funds will be added to the transaction to pay this invoice.
> * The resulting transaction will be saved to the file '/tmp/paid2.tx', which you can manually send back to the invoice creator.
> 
> The invoice slate's participant info is:
> 
> Participant ID 1 (Recipient)
> ---------------------
> Public Key: 03d0cf3f7ad98e0db1c31621705a1823dc87606c7027a7c766a789df5d8f94cbd1
> Message: None
> Message Signature: None
> 
> Please review the above information carefully before proceeding
> 
> To proceed, type the exact amount of the invoice as displayed above (or Q/q to quit) > 0.600000000
> 20190519 16:13:10.478 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /Users/mike/.grin/floo/wallet_data/wallet.seed
> 20190519 16:13:10.479 DEBUG grin_store::lmdb - DB Mapsize for /Users/mike/.grin/floo/wallet_data/db/lmdb is 549755813888
> 20190519 16:13:10.480 INFO grin_wallet_impls - Using LMDB Backend for wallet
> 20190519 16:13:10.498 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /Users/mike/.grin/floo/wallet_data/wallet.seed
> 20190519 16:13:10.776 DEBUG grin_wallet_libwallet::internal::updater - Refreshing wallet outputs
> 20190519 16:13:11.032 DEBUG grin_core::libtx::build - Building input (spending regular output): 304994100000, 0300000000000000000000002100000000
> 20190519 16:13:11.032 DEBUG grin_core::libtx::build - Building input (spending regular output): 304994100000, 0300000000000000000000002200000000
> 20190519 16:13:11.032 DEBUG grin_core::libtx::build - Building input (spending regular output): 304994100000, 0300000000000000000000002300000000
> 20190519 16:13:11.032 DEBUG grin_core::libtx::build - Building input (spending regular output): 304994100000, 0300000000000000000000002400000000
> 20190519 16:13:11.032 DEBUG grin_core::libtx::build - Building input (spending regular output): 304994100000, 0300000000000000000000002500000000
> 20190519 16:13:11.032 DEBUG grin_core::libtx::build - Building input (spending regular output): 304994100000, 0300000000000000000000002600000000
> 20190519 16:13:11.032 DEBUG grin_core::libtx::build - Building input (spending regular output): 304994100000, 0300000000000000000000002700000000
> 20190519 16:13:11.032 DEBUG grin_core::libtx::build - Building input (spending regular output): 304994100000, 0300000000000000000000002800000000
> 20190519 16:13:11.032 DEBUG grin_core::libtx::build - Building input (spending regular output): 304994100000, 0300000000000000000000002900000000
> 20190519 16:13:11.032 DEBUG grin_wallet_libwallet::internal::selection - Building change outputs: total change: 2744345900000 (1 outputs)
> 20190519 16:13:11.084 DEBUG grin_core::libtx::build - Building output: 2744345900000, Commitment(082dc12a3fa07e8d29d5c9d6c3adb7939da964a61302ad8ad09fe71362a4f28125)
> 20190519 16:13:11.177 INFO grin_wallet_controller::command - Invoice processed: 0.600000000 grin to /tmp/paid2.tx (strategy 'all')
> 20190519 16:13:11.178 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /Users/mike/.grin/floo/wallet_data/wallet.seed
> Command 'pay' completed successfully
> fw finalize -i /tmp/paid2.tx                                         
> 20190519 16:13:33.294 INFO grin_util::logger - log4rs is initialized, file level: Debug, stdout level: Debug, min. level: Debug
> 20190519 16:13:33.295 INFO grin_wallet - Using wallet configuration file at /Users/mike/.grin/floo/grin-wallet.toml
> 20190519 16:13:33.295 INFO grin_wallet - This is Grin Wallet version 1.1.0-beta.3 (git v1.1.0-beta.3-1-g94aee6f), built for x86_64-apple-darwin by rustc 1.33.0 (2aa4c46cf 2019-02-28).
> 20190519 16:13:33.295 DEBUG grin_wallet - Built with profile "release", features "".
> 20190519 16:13:33.295 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /Users/mike/.grin/floo/wallet_data/wallet.seed
> 20190519 16:13:33.295 DEBUG grin_store::lmdb - DB Mapsize for /Users/mike/.grin/floo/wallet_data/db/lmdb is 549755813888
> 20190519 16:13:33.296 INFO grin_wallet_impls - Using LMDB Backend for wallet
> 20190519 16:13:33.332 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /Users/mike/.grin/floo/wallet_data/wallet.seed
> Wallet command failed: LibWallet Error: LibTx Error

**Comment by yeastplume** [comment]
I just did a manual dry run of an invoice tx all the way through (using the user testing chain,) and all worked as expected. There are also a lot of automated tests exercising the process, and they're all passing fine.

Could you try again with RUST_BACKTRACE=1?

**Comment by mcdallas** [comment]
> Wallet command failed: LibWallet Error: LibTx Error
>  Backtrace: stack backtrace:
>    0: failure::backtrace::internal::InternalBacktrace::new::h621fac4efd93e35d (0x105d0e918)
>    1: <failure::backtrace::Backtrace as core::default::Default>::default::hf0fbeb05be4ddb50 (0x105d0eb14)
>    2: grin_wallet_libwallet::slate::Slate::verify_part_sigs::hcbc933bc99a4f3ff (0x1059bd8f6)
>    3: grin_wallet_libwallet::internal::tx::complete_tx::h08a93f27d2c15de5 (0x105710292)
>    4: grin_wallet_libwallet::api_impl::foreign::finalize_invoice_tx::ha11fda0dd263fcdd (0x1056af56a)
>    5: <grin_wallet_api::foreign::Foreign<W, C, K>>::finalize_invoice_tx::hb9573961919cadf9 (0x10571b864)
>    6: grin_wallet_controller::command::finalize::h16d2d7e821afe2b7 (0x10577a4f8)
>    7: grin_wallet::cmd::wallet_args::wallet_command::h17885a4aa91d8588 (0x1056feba3)
>    8: grin_wallet::cmd::wallet::wallet_command::hb0ebff83146833cc (0x1056a6d63)
>    9: grin_wallet::real_main::h058ab3c798fd4ae3 (0x1056bb339)
>   10: grin_wallet::main::h890edb8faa657a22 (0x1056ba728)
>   11: std::rt::lang_start::{{closure}}::h4d8a2cde4c9fd3f9 (0x1056c3865)
>   12: std::panicking::try::do_call::h5083b83567b39945 (0x105db8cc7)
>   13: ___rust_maybe_catch_panic (0x105dc1a7e)
>   14: std::rt::lang_start_internal::heccf345451899304 (0x105db96ed)
>   15: _main (0x1056bb748)
> Backtrace: stack backtrace:
>    0: failure::backtrace::internal::InternalBacktrace::new::h621fac4efd93e35d (0x105d0e918)
>    1: <failure::backtrace::Backtrace as core::default::Default>::default::hf0fbeb05be4ddb50 (0x105d0eb14)
>    2: <grin_wallet_controller::error::Error as core::convert::From<grin_wallet_libwallet::error::Error>>::from::h5aab12dbd49eb23a (0x105853b26)
>    3: grin_wallet_controller::command::finalize::h16d2d7e821afe2b7 (0x10577ae4f)
>    4: grin_wallet::cmd::wallet_args::wallet_command::h17885a4aa91d8588 (0x1056feba3)
>    5: grin_wallet::cmd::wallet::wallet_command::hb0ebff83146833cc (0x1056a6d63)
>    6: grin_wallet::real_main::h058ab3c798fd4ae3 (0x1056bb339)
>    7: grin_wallet::main::h890edb8faa657a22 (0x1056ba728)
>    8: std::rt::lang_start::{{closure}}::h4d8a2cde4c9fd3f9 (0x1056c3865)
>    9: std::panicking::try::do_call::h5083b83567b39945 (0x105db8cc7)
>   10: ___rust_maybe_catch_panic (0x105dc1a7e)
>   11: std::rt::lang_start_internal::heccf345451899304 (0x105db96ed)
>   12: _main (0x1056bb748)

Looks like the sig verification fails

**Comment by garyyu** [comment]
Does the problem still there?
I tried an invoice transaction with this `finalize` command, it works well.

**Comment by mcdallas** [comment]
@garyyu Yes and it happens every single time. I am on mac btw if that makes any difference

**Comment by mcdallas** [comment]
So this only happens only if you send an invoice to yourself. It happens to @garyyu as well. @yeastplume is issuing and paying an invoice from the same wallet supposed to work or you can't do that?

**Comment by yeastplume** [comment]
ahh, okay great. Yes it is supposed to work, I’ll look into it now

**Comment by yeastplume** [comment]
should be okay now, can you check with lastest master?

**Comment by mcdallas** [comment]
Yes it works now 👍
