### ISSUE TITLE
grin-wallet pay by http no implementation?

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin-wallet#116]
I tried with `grin-wallet pay -d http://ip:3415 -i inv1.tx -m http`
but it doesn't work.

Reading the code, look like there's no `finalize_invoice_tx` API calling on `http.rs` adapter.

Have this been forgot?  or miss it for purpose?

**Comment by yeastplume** [comment]
It's implemented in the V2 API only, as the V1 api will be going away very soon (The first thing I intend to do once branching after 1.1.0 release)
