### ISSUE TITLE
Recover fails in 1.1 beta-4

### ISSUE THREAD

**Issue by hashmap** [mimblewimble/grin-wallet#133]
It works on the same machine with 1.0.3

```
Error recovering seed: IO Error
Wallet command failed: Impls Error
```
nothing in logs

**Comment by yeastplume** [comment]
Can only get this when recovering without `wallet_data` directory in ~/.grin. This and #128 should be fixed by #134, which displays a more helpful error message if the wallet_data directory doesn't exist. Does that address it?

**Comment by hashmap** [comment]
I hope so, I just found that I have `grin-wallet.toml` in my home folder on this machine, so I assume even `~/.grin/wallet_data` existed (I created it) the wallet was expecting `~/wallet_data` to exists.

**Comment by yeastplume** [comment]
Okay, think we're good, closing for now
