### ISSUE TITLE
Last send transaction never confirmed when used up grin in the wallet

### ISSUE THREAD

**Issue by xiaojay** [mimblewimble/grin-wallet#135]
tested grin-wallet version: v1.1.0-beta.4

when user want use up all the grin in a wallet, he send all the grin to another user.

however the last send transaction never show confirmed locally even when the receiver's output commit is confirmed in blockchain.

**Comment by hashmap** [comment]
It's a know issue (can't find it for some reason), the problem is the wallet tracks a tx's state using the change output which doesn't exist in this case

**Comment by jaspervdm** [comment]
Yeah, i suggested its better to query the tx status by kernel instead of change output, but it would require a new node api call that does kernel lookup. Havent had the time to work on this myself.

**Comment by yeastplume** [comment]
Makes sense, definitely need to address this. In the meantime 'grin wallet check' should fix the issue when this happens

**Comment by bladedoyle** [comment]
I also had this issue - see: https://github.com/mimblewimble/grin-wallet/issues/69

**Comment by yeastplume** [comment]
Looking back at it, I think the linked issue was closed accidentally, but it's a duplicate of this one anyhow.
