### ISSUE TITLE
Trait Implementation error

### ISSUE THREAD

**Issue by xwen01** [mimblewimble/grin-wallet#136]
Hi, I am trying to use grin-wallet api to send funds. When I did command:
```
data=`cat tx03_test@abc.com_20190605.json`; curl -0 -XPOST -u grin:xxx http://127.0.0.1:3420/v1/wallet/owner/issue_send_tx  -d "$data" 1>post_tx03_test@abc.com_20190605.json
```
I got "Trait Implementation error". What is wrong here? 
Thanks for the help.

**Comment by yeastplume** [comment]
V1 api not relevant anymore, but please feel free to ask these kinds of questions in the gitter support channel, you'll likely have a better chance of having it answered quickly
