### ISSUE TITLE
Implement Wallet HTTP Client using V2 API

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin-wallet#138]
The wallet HTTP client that communicates with other wallets is currently implemented using the V1 API (even when using the V2 API itself). Since the V1 API is being removed, the calls to other clients have to be implemented using V2

**Comment by bddap** [comment]
The auto generated client helpers will be useful in this endeavor https://docs.rs/grin_wallet_api/1.1.0/grin_wallet_api/enum.foreign_rpc_client.html

**Comment by kargakis** [comment]
Fixed by https://github.com/mimblewimble/grin-wallet/pull/144 ?
