### ISSUE TITLE
Add wallet initialization api to owner api?

### ISSUE THREAD

**Issue by xiaojay** [mimblewimble/grin-wallet#14]
It will be much convenient  for third-part developer(like web wallet developer) to add a  wallet initialization api to owner api.

This api should have the same function like command ["grin wallet init"](https://github.com/mimblewimble/docs/wiki/how-to-use-the-grin-wallet#initialize-the-wallet)
Api user could post password and return 24 word recovery phrase if wallet is initialized successfully.

thanks.

**Comment by yeastplume** [comment]
Agreed this is needed at some stage, happy to leave this issue open as a reminder.

**Comment by yeastplume** [comment]
Currently working on an RFC to address this: https://github.com/yeastplume/grin-rfcs/blob/master/grinrfc-0000-full-wallet-lifecycle.md

**Comment by yeastplume** [comment]
Now implemented, see #212
