### ISSUE TITLE
going back and forth between v1.1.0 and v1.0.3 server and wallets messed up the chain files and/or wallet, and recover/restore/check doesn't work

### ISSUE THREAD

**Issue by aleqx** [mimblewimble/grin-wallet#150]
I don't know if this is a grin or grin-wallet issue. I'll open a grin issue as well and just link here. I'm left with a non-working wallet which I could not fix at all. 

I'm on Ubuntu 16.04.5. Here's what happened.

- I had v1.0.2 which was working fine. I then updated to v1.0.3 which also worked fine, wallet too.
- Then I updated to 1.1.0. I started the grin server via `grin`. It all looked fine.
- I downloaded the new `grin-wallet` v1.1.0 and used it to send GRIn to Bittrex successfully. Also used to receive GRIN successfully from Poloniex and a few others. ALl fine so far.
- I then tried to send GRIN to Poloniex and hit the `Wallet command failed: LibWallet Error: Can't Deserialize slate` problem which I reported here https://github.com/mimblewimble/grin-wallet/issues/145
- at this point `grin-wallet info` showed:
```
# grin-wallet info
Password:

____ Wallet Summary Info - Account 'default' as of height 214024 ____

 Confirmed Total                  | 132.447773890
 Awaiting Confirmation (< 10)     | 0.000000000
 Awaiting Finalization            | 0.000000000
 Locked by previous transaction   | 0.000000000
 -------------------------------- | -------------
 Currently Spendable              | 132.447773890

Command 'info' completed successfully
```
- I tried forcing -v 1 and -v 0 thinking Poloniex does not support something in the new slate format, which failed with the same error.
- I then tried to go back to v1.0.3. I stopped grin-1.1.0 server which had been running for a few days. I started grin-1.0.3 **over the same chain data** (is this a problem?)
- I did a `grin wallet info` (this is v1.0.3) which showed all 0's:
```
# grin wallet info
Password:

____ Wallet Summary Info - Account 'default' as of height 214024 ____

 Total                            | 0.000000000
 Awaiting Confirmation (< 10)     | 0.000000000
 Locked by previous transaction   | 0.000000000
 -------------------------------- | -------------
 Currently Spendable              | 0.000000000

Command 'info' completed successfully
```
- I said fine, let's `check` it to fix it, so I did:
```
# grin wallet check
Password:
20190613 23:11:10.320 WARN grin_wallet::command - Starting wallet check...
20190613 23:11:10.320 WARN grin_wallet::command - Updating all wallet outputs, please wait ...
20190613 23:11:10.433 WARN grin_wallet::libwallet::internal::restore - Starting wallet check.
20190613 23:11:11.026 WARN grin_wallet::libwallet::internal::restore - Checking 1000 outputs, up to index 1260291. (Highest index: 24334)
20190613 23:11:11.026 WARN grin_wallet::libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
20190613 23:11:12.116 WARN grin_wallet::libwallet::internal::restore - Checking 1000 outputs, up to index 1260291. (Highest index: 52072)
20190613 23:11:12.116 WARN grin_wallet::libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
20190613 23:11:13.174 WARN grin_wallet::libwallet::internal::restore - Checking 1000 outputs, up to index 1260291. (Highest index: 108903)
20190613 23:11:13.174 WARN grin_wallet::libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
...
<snip>
...
20190613 23:11:55.488 WARN grin_wallet::libwallet::internal::restore - Confirmed output for 132447773890 with ID 0300000000000000000000006f00000000 (Commitment(092c045dde6d564270d9c9ff9b818e2d2e777b46bbad121648785049e68d22155f)) exists in UTXO set but not in wallet. Restoring.
20190613 23:11:55.511 WARN grin_wallet::command - Wallet check complete
Command 'check' completed successfully
```
which looked fine since 132447773890 is the actual amount I know the wallet had, so I thought it was fixed. but when I did `grin wallet info` I got:
```
# grin wallet info
Password:

____ Wallet Summary Info - Account 'default' as of height 214029 ____

 Total                            | 0.000000000
 Awaiting Confirmation (< 10)     | 0.000000000
 Locked by previous transaction   | 0.000000000
 -------------------------------- | -------------
 Currently Spendable              | 0.000000000
```
**WTF?!?!**
- I then did a `grin-wallet info` (this is 1.1.0) which the grin server 1.0.3 running, and I got:
```
# grin-wallet info
Password:

____ Wallet Summary Info - Account 'default' as of height 214029 ____

 Confirmed Total                  | 264.895547780
 Awaiting Confirmation (< 10)     | 0.000000000
 Awaiting Finalization            | 0.000000000
 Locked by previous transaction   | 0.000000000
 -------------------------------- | -------------
 Currently Spendable              | 264.895547780

Command 'info' completed successfully
```
**WTF?!?!?!?!?** ... that's double the amount!
- I then stopped grin-1.0.3 server and started the grin-1.1.0 server. Then I did `grin-wallet info` again and got:
```
# grin-wallet info
Password:

____ Wallet Summary Info - Account 'default' as of height 214029 ____

 Confirmed Total                  | 264.895547780
 Awaiting Confirmation (< 10)     | 0.000000000
 Awaiting Finalization            | 0.000000000
 Locked by previous transaction   | 0.000000000
 -------------------------------- | -------------
 Currently Spendable              | 264.895547780

Command 'info' completed successfully
```
WTF?
- I then tried a `grin-wallet check` (this is the 1.1.0 wallet using the 1.1.0 server) and got:
```
gw check
20190613 23:12:28.997 WARN grin_wallet_controller::command - Starting wallet check...
20190613 23:12:28.997 WARN grin_wallet_controller::command - Updating all wallet outputs, please wait ...
20190613 23:12:29.115 WARN grin_wallet_libwallet::internal::restore - Starting wallet check.
20190613 23:12:29.689 WARN grin_wallet_libwallet::internal::restore - Checking 1000 outputs, up to index 1260295. (Highest index: 24334)
20190613 23:12:29.689 WARN grin_wallet_libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
20190613 23:12:30.777 WARN grin_wallet_libwallet::internal::restore - Checking 1000 outputs, up to index 1260295. (Highest index: 52072)
20190613 23:12:30.777 WARN grin_wallet_libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
20190613 23:12:31.843 WARN grin_wallet_libwallet::internal::restore - Checking 1000 outputs, up to index 1260295. (Highest index: 108903)
20190613 23:12:31.844 WARN grin_wallet_libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
...
<snip>
...
20190613 23:13:12.534 WARN grin_wallet_libwallet::internal::restore - Checking 1000 outputs, up to index 1260295. (Highest index: 1258887)
20190613 23:13:12.534 WARN grin_wallet_libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
20190613 23:13:13.579 WARN grin_wallet_libwallet::internal::restore - Checking 980 outputs, up to index 1260295. (Highest index: 1260295)
20190613 23:13:13.580 WARN grin_wallet_libwallet::internal::restore - Scanning 980 outputs in the current Grin utxo set
20190613 23:13:14.048 WARN grin_wallet_libwallet::internal::restore - Identified 1 wallet_outputs as belonging to this wallet
20190613 23:13:14.050 WARN grin_wallet_controller::command - Wallet check complete
Command 'check' completed successfully
```
Ok ... then I did a `grin-wallet info` and got again:
```
# grin-wallet info
Password:

____ Wallet Summary Info - Account 'default' as of height 214029 ____

 Confirmed Total                  | 264.895547780
 Awaiting Confirmation (< 10)     | 0.000000000
 Awaiting Finalization            | 0.000000000
 Locked by previous transaction   | 0.000000000
 -------------------------------- | -------------
 Currently Spendable              | 264.895547780

Command 'info' completed successfully
```
- I backed up the wallet folder, recovered the seed file from the passphrase, then restored the wallet from the seed file, then tried `grin-wallet info` again ... same thing: double the amount.
- I then tried to transfer 1 GRIN to one of my own other wallets running elsewhere and got (this is with grin-1.1.0 server and grin-wallet-1.1.0):
```
grin-wallet send -d http://grin1.<snip>:3415 1
20190613 23:13:45.052 ERROR grin_wallet_impls::adapters::http - Posting transaction slate (is recipient listening?): Request error: Wrong response code: 500 Internal Server Error with data Body
Wallet command failed: LibWallet Error: Client Callback Error: Posting transaction slate (is recipient listening?): Request error: Wrong response code: 500 Internal Server Error with data Body
```
WTF?!? The other wallet reported:
```
20190614 00:13:45.042 ERROR grin_wallet_controller::controller - receive_tx: failed with error: Fee Error: Fee Dispute Error: 7000000, 8000000
20190614 00:13:45.042 ERROR grin_wallet_controller::controller - Request Error: Error { inner:

Fee Error: Fee Dispute Error: 7000000, 8000000 }
```
**Fee Dispute Error**?!?

I'm out of ideas of how to fix it. I renamed the `.grin` folder to `.grin~` and I'm now restoring the full chain data using the grin-1.0.3 server, and then I'll restore the wallet using the grin-1.0.3 wallet and hope for the best.

Anyone has any clues?

p.s. I usually never touch x.y.0 software versions ... don't know why I did this time.
p.p.s. I see 1.0.3 has issues sending to several exchanges ... going back to 1.0.2 :(

**Comment by bladedoyle** [comment]
see also:  https://github.com/mimblewimble/grin-wallet/issues/141

**Comment by bladedoyle** [comment]
You will have to restore your wallet from seed.

1) stop all wallet processes

2) move your wallet data to a backup name
cd ~/.grin/main
mv wallet_data wallet_data.bak

3) make a new wallet_data directory and copy your seed there
mkdir wallet_data
cp wallet_data.bak/wallet.seed wallet_data/

4) make sure you have a server running, and that its fully synced

5) restore the wallet
grin-wallet restore

**Comment by aleqx** [comment]
Restoring from seed using either wallet versions (v1.1.0 or 1.0.3) didn't fix anything ... I tried both grin server versions too (1.1.0 and 1.0.3). It seems the chain files got screwed, not the wallet. I had to wipe everything and restart from 0:

- delete `~/.grin`
- started `grin` 1.0.2
- waited to sync the full chain
- used grin wallet 1.0.2 and recovered the seed from passphrase using `grin wallet recover` then restored the wallet from seed using `grin wallet restore`

Funds are now correct and accessible again.

It seems that the chain files got damaged, not the wallet.

Either way, I'm staying away from 1.1.0 :)

**Comment by jaspervdm** [comment]
The root of your difficulties lies most likely in the fact that you didn't follow the node-wallet compatibility chart in [the announcement](https://www.grin-forum.org/t/upgrade-information-grin-v1-1-0/5147). wallet v1.1 is not compatible with node v1.0.3.
Incompatibility with Poloniex has been reported before, but this is not something that we can change on the wallet side, it has to be fixed by the exchange.

**Comment by aleqx** [comment]
I was running 1.1.0 for both node and wallet when the problem occurred. I tried to go back after the problem occurred in an attempt to access the funds but things got more and more screwy

**Comment by jaspervdm** [comment]
In wallet 1.1 there are slight changes to how outputs are stored in the backend, in a way that 1.1 can read data from 1.0.3 but 1.0.3 cannot read from 1.1. This completely explains your situation. You did another `check` at 1.0.3, which created the same entries in the db, so when you go to 1.1 again you see each output twice. Moral of the story: don't use the same db when you downgrade from 1.1 to 1.0.3, `restore` from seed. Or don't downgrade in the first place

**Comment by aleqx** [comment]
I understand. Still, as I explained, restoring from seed made no difference. I had to wipe the chain files as well.
