### ISSUE TITLE
grin node does not run in macOS Mojave

### ISSUE THREAD

**Issue by tomtang539** [mimblewimble/grin-wallet#151]
Downloaded 1.1.0 release.  Running grin hangs.  Running grin --floonet and usernet both behave as expected.

**Comment by Incrediblez7** [comment]
It works for me. I am using macOS Mojave. Try resetting grin-server.toml?

**Comment by kargakis** [comment]
Why is this issue opened in grin-wallet? Please close and reopen in mimblewimble/grin including your `grin-server.log`

**Comment by tomtang539** [comment]
@Incrediblez7  that worked.  thanks.  Sorry for opening this in the wrong project.
