### ISSUE TITLE
An error occurred "Wallet command failed: LibWallet Error: Can't parse slate version"

### ISSUE THREAD

**Issue by uranusdesigner** [mimblewimble/grin-wallet#152]
I have try to receive coins via file:  ./grin-wallet receive -i transaction.tx
and An error occurred
Password: 
Wallet command failed: LibWallet Error: Can't parse slate version

grin:v1.1.0
grin wallet : v1.1.0-beta.3

I'm a newbie and don't know how to fix it, please help me!!!

**Comment by aleqx** [comment]
You can try to force the slate version when sending by using `send -m file -d tr.tx -v 1` .. 0/1/2 are valid slate versions in 1.1.0, try all of them.

p.s. You will first want to cancel the one you created by doing `grin-wallet cancel -i txid` (you can find out the id by doing `grin-wallet txs`)

**Comment by uranusdesigner** [comment]
okay. I will do it, hope everything will be good, thank you.

**Comment by uranusdesigner** [comment]
> It should work if you created the slate using 1.1.0. Why are you still using an older beta of thee wallet? Best to first upgrade the wallet to 1.1.0 final. You can then try to force the slate version when creating the slate file `grin-wallet send -m file -d tr.tx -v 1 50.0` ... 0/1/2 are valid slate versions in 1.1.0, you can try all of them.
> 
> p.s. You will first want to cancel the one you created by doing `grin-wallet cancel -i txid` (you can find out the id by doing `grin-wallet txs`)

Thanks for reply! I will do it, hope everything will be good!

**Comment by uranusdesigner** [comment]
> It should work if you created the slate using 1.1.0. Why are you still using an older beta of thee wallet? Best to first upgrade the wallet to 1.1.0 final. You can then try to force the slate version when creating the slate file `grin-wallet send -m file -d tr.tx -v 1 50.0` ... 0/1/2 are valid slate versions in 1.1.0, you can try all of them.
> 
> p.s. You will first want to cancel the one you created by doing `grin-wallet cancel -i txid` (you can find out the id by doing `grin-wallet txs`)

Thanks for your help!!! problem fixed!!!
