### ISSUE TITLE
cannot retrieve txs with Query APIs

### ISSUE THREAD

**Issue by xwen01** [mimblewimble/grin-wallet#156]
I have made some send transactions using grin-wallet API and am able to see the transaction confirmed in the output of "grin-wallet txs" command. However, when I use the "Shared Transaction Id" to retrieve the transaction, I got no response. The command I used is:

```
curl -0 -XGET http://127.0.0.1:3420/v1/wallet/owner/retrieve_txs?tx_id=70b660b0-a126-46e4-9f6f-517d9c3c2be4 2>/dev/null | jq
```
What am I doing wrong here? Thanks for the help.

**Comment by bladedoyle** [comment]
One possible cause is that your query is Unauthorized.   Try adding a "-I" to your curl command and see if you get "401 Unauthorized".  If so, you can add basicauth to your request.

**Comment by xwen01** [comment]
> One possible cause is that your query is Unauthorized. Try adding a "-I" to your curl command and see if you get "401 Unauthorized". If so, you can add basicauth to your request.
> 
> ```
> # curl -0 -I -XGET http://127.0.0.1:3420/v1/wallet/owner/retrieve_txs
> HTTP/1.0 401 Unauthorized
> www-authenticate: Basic realm=GrinOwnerAPI
> content-length: 0
> date: Tue, 18 Jun 2019 15:14:47 GMT
> ```

That works! Thank you!
