### ISSUE TITLE
LibWallet Error with grin-wallet -e listen

### ISSUE THREAD

**Issue by joss3js** [mimblewimble/grin-wallet#159]
Hello team,

I tried grin node: grin-v2.0.0-beta.1-linux-amd64
grin wallet: grin-wallet-v2.0.0-beta.1-linux-amd64

changed api_listen_interface = "0.0.0.0"

then: ./grin-wallet -e listen
```
Password:
20190621 05:48:09.360 WARN grin_wallet_controller::controller - Starting HTTP Foreign listener API server at 0.0.0.0:3415.
Wallet command failed: LibWallet Error: Generic error: API thread failed to start
```
Could you please address the issue?

**Comment by yeastplume** [comment]
Don't see this issue locally. Is there anything special about your environment that might cause this? Thread limits or the like?

**Comment by joss3js** [comment]
Yes, the issue was seen when it was running on 1 core CPU. It works well since I install with 2 cores CPU.

**Comment by yeastplume** [comment]
Going to close this as error seems fairly local
