### ISSUE TITLE
sending consecutive transactions using wallet sending api

### ISSUE THREAD

**Issue by xwen01** [mimblewimble/grin-wallet#161]
Hi,
I am trying to send consecutive transactions using the wallet sending api. The first send transaction was successful. However, once the first was sent, the wallet "Currently Spendable" amount will turn to 0 so the second send transaction will fail with "Not enough funds" error. 

Do you have any suggestion how should I send more than one transactions consecutively using the Grin Wallet API?

**Comment by jaspervdm** [comment]
Make sure you have multiple outputs available, you can send a tx with `num_change_outputs` set to a higher value. Also, send with the `smallest` strategy, `all` will spend all your outputs in a single tx.

**Comment by xwen01** [comment]
> Make sure you have multiple outputs available, you can send a tx with `num_change_outputs` set to a higher value. Also, send with the `smallest` strategy, `all` will spend all your outputs in a single tx.

Thanks for your reply. I have "selection_strategy_is_use_all": false. For the `num_change_outputs`, how should I decide what number to use?

**Comment by xwen01** [comment]
> > Make sure you have multiple outputs available, you can send a tx with `num_change_outputs` set to a higher value. Also, send with the `smallest` strategy, `all` will spend all your outputs in a single tx.
> 
> Thanks for your reply. I have "selection_strategy_is_use_all": false. For the `num_change_outputs`, how should I decide what number to use?

Some update: 
I put more funds into the wallet, then consecutive sends were successful. There were enough funds for the two send transactions I got error from, but wallet balance was under 1.5 grin. Is it something normal?

Thanks.

**Comment by xwen01** [comment]
> Make sure you have multiple outputs available, you can send a tx with `num_change_outputs` set to a higher value. Also, send with the `smallest` strategy, `all` will spend all your outputs in a single tx.

Some update:
I put more funds into the wallet, then consecutive sends were successful. There were enough funds for the two send transactions I got error from, but wallet balance was under 1.5 grin. Is it something normal?

Thanks.

**Comment by bladedoyle** [comment]
This may be related: https://github.com/mimblewimble/grin/issues/2868

**Comment by yeastplume** [comment]
Looks resolved, please feel free to reopen if not
