### ISSUE TITLE
All APIs call return 404

### ISSUE THREAD

**Issue by ciaos** [mimblewimble/grin-wallet#163]
I start node like this
/root/grin-wallet/grin-wallet owner_api
/root/grin-wallet/grin-wallet -e listen
I found port 3420 and 3415 both listend.

But I can't make any API call. (get balance \ list unspent)

Version 1.0.2 worked well. version 2.0.0 returns 404

**Comment by ciaos** [comment]
I found all APIs changed.

1. Is there a document about how to make a transfer?
2. Where is the repost method. (/v1/wallet/owner/repost?fluff)

**Comment by yeastplume** [comment]
The V1 API is removed in 2.0.0, please see the announcement from a few weeks ago here, which have links to the new wallet APIs: https://www.grin-forum.org/t/grin-first-hard-fork-mid-july/5148
