### ISSUE TITLE
init_send_tx RPC does not work with "send_args" - InvalidArgStructure "args" at position 0."

### ISSUE THREAD

**Issue by GHLover** [mimblewimble/grin-wallet#171]
Utilizing the following documentation:
1. https://github.com/mimblewimble/grin-wallet/blob/master/api/src/owner.rs
2. https://github.com/mimblewimble/grin-wallet/blob/master/libwallet/src/api_impl/types.rs
3. https://github.com/mimblewimble/grin-wallet/blob/master/api/src/owner_rpc.rs

Utilizing "init_send_tx" does not work when "send_args" is a value other than null (None). With non-null vaues it returns InvalidArgStructure "args" at position 0."

**Test RPC Call**
```
{
  "args": {
    "src_acct_name": null,
    "amount": "1000000000",
    "max_outputs": 500,
    "minimum_confirmations": 10,
    "num_change_outputs": 1,
    "selection_strategy_is_use_all": true,
    "message": "my message",
    "target_slate_version": null,
    "send_args": {
      "method": "http",
      "dest": "http://127.0.0.1:3415",
      "finalize": true,
      "post": true,
      "fluff": true
    }
  }
}
```

**RPC Response**

```
{
  "error": {
    "code": -32602,
    "message": "InvalidArgStructure \"args\" at position 0."
  },
  "id": 6,
  "jsonrpc": "2.0"
}
```

Call works and slate is returned as long as "send_args" is undefined. If that is defined, then it no longer works.

Any guidance is appreciated.

**Comment by yeastplume** [comment]
`"post" : true`

should be

`post_tx: true`

Please let me know if that fixes it

**Comment by GHLover** [comment]
Yes, it does work. Thank you
