### ISSUE TITLE
grin-wallet v2.0.0's command "grin-wallet -V" show wrong version name?

### ISSUE THREAD

**Issue by xiaojay** [mimblewimble/grin-wallet#173]
The latest release grin-wallet v2.0.0's command "grin-wallet -V"  still show "grin-wallet 2.0.0-beta.2".
Is it expected?

**Comment by yeastplume** [comment]
No, it's an oversight and thanks for pointing it out. Unfortunately it's too late to fix this for 2.0.0, but all future versions will ensure the output string is correct. See #174 which will address this

**Comment by yeastplume** [comment]
This should be fixed now by #174, with equivalent fix on the node side. Thanks!
