### ISSUE TITLE
grin-wallet v2.0.0 reports version 2.0.0-beta.2

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin-wallet#175]
```
$ git status
HEAD detached at v2.0.0
nothing to commit, working directory clean
$ ./grin-wallet --version
grin-wallet 2.0.0-beta.2
```

**Comment by jaspervdm** [comment]
This has been fixed with this commit: https://github.com/mimblewimble/grin-wallet/commit/21dd3d53770f301353f124a8271ae96ab761ba93. Unfortunately we cannot easily re-tag v2.0.0 but in future versions this shouldn't happen again.

**Comment by bladedoyle** [comment]
Ok, Probably safe to close this if its already resolved in master.
