### ISSUE TITLE
Send through owner api not working

### ISSUE THREAD

**Issue by wsy2220** [mimblewimble/grin-wallet#177]
After using "init_send_tx", the wallet does not save generated tx. So we cann't retrive, cancel or finalize tx, which means transaction through api completely unusable.

**Comment by yeastplume** [comment]
Please see this post https://www.grin-forum.org/t/issue-send-tx-equivalent-in-the-v2-wallet-api/5426

**Comment by wsy2220** [comment]
> Please see this post https://www.grin-forum.org/t/issue-send-tx-equivalent-in-the-v2-wallet-api/5426

I tried, it did work. However if the wallet doesn't save used outputs after send, we cann't send more before the receiver replys, since we cannot control which output it will use for next tx.

**Comment by yeastplume** [comment]
I'm not sure what you mean, but if you try `"selection_strategy_is_use_all": false` , it should only lock the minimum number of outputs needed for the transaction, not all of them.

**Comment by xwen01** [comment]
> I'm not sure what you mean, but if you try `"selection_strategy_is_use_all": false` , it should only lock the minimum number of outputs needed for the transaction, not all of them.

Hi @yeastplume ,
I am having some issue with "init_send_tx" hope you can help. First of all, when I try to send by using "init_send_tx" API, it returns error with "NotEnoughFunds". However, there are enough funds in "Currently Spendable" in my wallet. Command I tried:
```
curl -0 -XPOST -u grin:`cat /root/.grin/main/.api_secret` --data '{ "jsonrpc": "2.0", "method": "init_send_tx", "params": {"args":{"src_acct_name":null, "amount":20000000, "minimum_confirmations":10, "max_outputs":500, "num_change_outputs":1, "selection_strategy_is_use_all":false, "message":null, "target_slate_version":null, "estimate_only":null, "send_args": {"method":"http", "dest":"https://grin.gateio.live/deposit/gateiogrin/xxxx", "finalize":true, "post_tx":true, "fluff":false}}}, "id": 1}' http://127.0.0.1:13420/v2/owner
```
Second, how can I do two or more sends consecutively with "init_send_tx"? Just set ```"selection_strategy_is_use_all": false```?

Thank you for any suggestion!

**Comment by yeastplume** [comment]
Closing as no update.
