### ISSUE TITLE
Add support for Murch's algorithm / Branch & Bound coin selection strategy

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-wallet#179]
https://gitter.im/grin_community/dev?at=5d1f3cb2c5f3c329aeec5241:

> Mark Renten @rentenmark 13:04
> grin should implement branch and bound as in [bitcoin/bitcoin#10637](https://github.com/bitcoin/bitcoin/pull/10637)
> it is the gold standard for utxo selection
> i would love to but i just don't have the time to work on it outside of work
> 
> ...
> 
> David Burkett @DavidBurkett 14:04
> @rentenmark It may be the gold standard for bitcoin, but how can we be sure that's true for grin? Grin is completely different for several reasons, most notably that inputs decrease the tx fee, not increase it. At this point, I'm not sure anyone has studied the problem enough to know which strategy is best
> 
> Mark Renten @rentenmark 15:19
> @DavidBurkett we have done quite a bit of thinking about it and for our use case this is the best one
> the "smallest" is .. alright
> 
> David Burkett @DavidBurkett 16:10
> The "smallest" is great for the Grin network, but far from ideal for usability, for privacy, and for limiting fees.

**Comment by yeastplume** [comment]
This is very much RFC territory, so please feel free to open one (or just discuss with the wallet subteam first).
