### ISSUE TITLE
the foreign api needs basic auth when using owner_api

### ISSUE THREAD

**Issue by viteshan** [mimblewimble/grin-wallet#183]
and this causes the send_tx_sync method to fail.

**Comment by roymoro** [comment]
curl -0 -XPOST -u grin:`cat ~/.grin/main/.api_secret` --data '{ "jsonrpc": "2.0", "method": "init_send_tx", "params": {"args":{"src_acct_name":null, "amount":10000000, "minimum_confirmations":10, "max_outputs":500, "num_change_outputs":1, "selection_strategy_is_use_all":true, "message":null, "target_slate_version":null, "estimate_only":null, "send_args": {"method":"http", "dest":"http://127.0.0.1:3420", "finalize":true, "post_tx":true, "fluff":true}}}, "id": 1}' http://127.0.0.1:3420/v2/owner
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "Err": {
      "ClientCallback": "Performing version check (is recipient listening?): Request error: Wrong response code: 401 Unauthorized with data Body"
    }
  }
}

**Comment by yeastplume** [comment]
Fixed in #218
