### ISSUE TITLE
Finalising a processed invoice always fails (floonet)

### ISSUE THREAD

**Issue by michaeldzjap** [mimblewimble/grin-wallet#185]
### Versions
Grin: v2.0.0
Grin Wallet: v2.0.0
net: floonet

### Issue
Everytime I try to finalise a processed invoice it fails with error

```
ERROR grin_api::handlers::chain_api - Failure to get output for commitment {someHash} with error Not found.
```

where {someHash} is equal to the "commit" property of the first entry in the outputs array of my slate file.

### Steps to reproduce
1. Issue an invoice using the first wallet:

```
curl -v -u grin:secret -d '{"jsonrpc": "2.0", "method": "issue_invoice_tx", "params": {"args": {"amount": "50000000", "message": "Issue invoice test", "dest_acct_name": null, "target_slate_version": null}}, "id": 1}' -H "Content-Type: application/json" -H "Accept: application/json" -X POST http://127.0.0.1:3420/v2/owner
```

2. Process the slate that was returned by step 1 using the second wallet:

```
curl -v -u grin:secret -d '{"jsonrpc": "2.0", "method": "process_invoice_tx", "params": [{slateFromStep1}, {"src_acct_name":null,"amount":"0","minimum_confirmations":2,"max_outputs":500,"num_change_outputs":1,"selection_strategy_is_use_all":true,"message":"Process invoice test","target_slate_version":null,"send_args":null}], "id": 1}' -H "Content-Type: application/json" -H "Accept: application/json" -X POST http://127.0.0.1:3420/v2/owner
```

3. Finalise the slate returned by step 2 using the first wallet

```
curl -v -u grin:secret -d '{"jsonrpc": "2.0", "method": "finalize_invoice_tx", "params": [{slateFromStep2}], "id": 1}' -H "Content-Type: application/json" -H "Accept: application/json" -X POST http://127.0.0.1:3420/v2/foreign
```

This seems to return the same slate as was used as the parameter to the `finalize_invoice_tx` call.

4. Retrieve the summary of information for the first wallet:

```
curl -v -u grin:secret -d '{"jsonrpc": "2.0", "method": "retrieve_summary_info", "params": [true, 10], "id": 1}' -H "Content-Type: application/json" -H "Accept: application/json" -X POST http://127.0.0.1:3420/v2/owner
```

The grin server now outputs an error of the form:

```
20190712 15:00:57.112 ERROR grin_api::handlers::chain_api - Failure to get output for commitment {someHash} with error Not found.
```

### Result

As said before {someHash} is equal to the "commit" property of the first entry in the outputs array of my slate file.

### Expected Result

Provided I executed the invoice flow correctly, I would have expected that I would not see the reported error and that the transaction clears (which it doesn't). Only cancelling the transaction seems to fix things.

**Comment by yeastplume** [comment]
Is this still occurring?

**Comment by michaeldzjap** [comment]
I had to put my Grin project on hold due to other work commitments unfortunately, so I haven't tried recently. One thing I still wanted to try is if I could get it to work if I issued and processed the invoice using the same wallet. I think that should be possible right?

Maybe I will find time to do this later this week, but if you want to go ahead and close this issue its fine with me.

**Comment by michaeldzjap** [comment]
I just had another go using v2.1.0-beta.1 using the same wallet for issuing and processing an invoice. However, when I try to process the invoice:

```
curl -v -u grin:`cat ~/.grin/floo/.owner_api_secret` -d '{"jsonrpc": "2.0", "method": "process_invoice_tx", "params": [{slateFromStep1}, {"src_acct_name":null,"amount":"0","minimum_confirmations":2,"max_outputs":500,"num_change_outputs":1,"selection_strategy_is_use_all":true,"message":"Process invoice test","target_slate_version":null,"send_args":null}], "id": 1}' -H "Content-Type: application/json" -H "Accept: application/json" -X POST http://127.0.0.1:3420/v2/owner
```

I get a `NotEnoughFunds` error back:

```json
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "Err": {
            "NotEnoughFunds": {
                "available": 0,
                "available_disp": "0.000000000",
                "needed": 55000000,
                "needed_disp": "0.055000000"
            }
        }
    }
}
```

However, when I check my wallet balance:

```
curl -v -u grin:`cat ~/.grin/floo/.owner_api_secret` -d '{"jsonrpc": "2.0", "method": retrieve_summary_info", "params": [true, 10], "id": 1}' -H "Content-Type: application/json" -H "Accept: application/json" -X POST http://127.0.0.1:3420/v2/owner
```

I see:

```json
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "Ok": [
            true,
            {
                "amount_awaiting_confirmation": "0",
                "amount_awaiting_finalization": "50000000",
                "amount_currently_spendable": "25910000000",
                "amount_immature": "0",
                "amount_locked": "0",
                "last_confirmed_height": "237620",
                "minimum_confirmations": "10",
                "total": "25910000000"
            }
        ]
    }
}
```

which should be more than enough to cover the invoice process request. Would you have any idea what goes wrong here?

**Comment by michaeldzjap** [comment]
Ok, so after a full resync of my node (floonet) I still run into my same original problem; I get a:

```
ERROR grin_api::handlers::chain_api - Failure to get output for commitment {someHash} with error Not found.
```

after attempting to finalise an invoice. Only cancelling the transaction gets rid of that error.

**Comment by yeastplume** [comment]
Okay, thanks for the detail. I'll run a quick verification test this week just to make sure there's nothing obviously wrong, then we can look in more detail

**Comment by yeastplume** [comment]
I've definitely been able to process invoices in later versions of the code (v3.0.0), and this does look like a node sync issue. Please let me know if this happens after upgrading to 3.0.0

**Comment by yeastplume** [comment]
Closing, please feel free to reopen if you run into this again, or try the support channel in keybase grincoin#support
