### ISSUE TITLE
No --config_file option. Inability to set custom config file and directories

### ISSUE THREAD

**Issue by RWGuy** [mimblewimble/grin-wallet#187]
The software operates on hard coded paths. Thus, it cannot meet the needs of any user with a custom path requirement. Unlike with grin server, there is not even an ability to specify a custom config file via --config_file. There is no way to run grin wallets with multiple configuration as a result.

I think it would make sense to make it possible to run custom directories. Setting a --config_file for example where any run directories can be set.

**Comment by BitHighlander** [comment]
:( this makes it very hard for a user to run multiple wallets on the same system

**Comment by yeastplume** [comment]
There is, just init a wallet with `grin-wallet init -h` which sets up the configuration in the current directory as opposed to the user directory. Going to close as I think the setup and workflow of paths are all working fine at the moment, (they're not hardcoded, they just assume a set of directories by default) but feel free to discuss with the wallet subteam and/or open an RFC if you don't think so.
