### ISSUE TITLE
http/s init_send_tx issue?

### ISSUE THREAD

**Issue by bxlkm** [mimblewimble/grin-wallet#188]
curl -0 -XPOST --user grin:XXXX -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0", "method":"init_send_tx", "params":{"args":{"src_acct_name":null, "amount":1000000000, "minimum_confirmations":10, "max_outputs":100, "num_change_outputs":1, "selection_strategy_is_use_all":true, "message":"i am verygood", "target_slate_version":null, "estimate_only":null, "send_args":{"method":"http", "dest":"https://XXXXXXX", "finalize":true, "post_tx":true, "fluff":false}}}, "id": 1}' http://127.0.0.1:3520/v2/owner

return:
 ERROR grin_wallet_impls::adapters::http - Posting transaction slate: Error: null, Message: null
Wallet command failed: LibWallet Error: Client Callback Error: Posting transaction slate: Error: null, Message: null

**Comment by yeastplume** [comment]
Looks like a configuration issue somewhere, did you manage to resolve this?

**Comment by dyzz** [comment]
Had a similar issue using "grin-wallet" cli.

Log:

> 20190820 06:03:51.360 INFO grin_util::logger - log4rs is initialized, file level: Trace, stdout level: Warn, min. level: Trace
> 20190820 06:03:51.361 INFO grin_wallet - Using wallet configuration file at /root/.grin/main/grin-wallet.toml
> 20190820 06:03:51.361 INFO grin_wallet - This is Grin Wallet version 2.0.0 (git v2.0.0), built for x86_64-unknown-linux-gnu by rustc 1.35.0 (3c235d560 2019-05-20).
> 20190820 06:03:51.361 DEBUG grin_wallet - Built with profile "release", features "".
> 20190820 06:03:51.365 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /root/.grin/main/wallet_data/wallet.seed
> 20190820 06:03:51.365 DEBUG grin_store::lmdb - DB Mapsize for /root/.grin/main/wallet_data/db/lmdb is 134217728
> 20190820 06:03:51.365 TRACE grin_store::lmdb - DB map size: 134217728
> 20190820 06:03:51.365 TRACE grin_store::lmdb - Space used: 4464640
> 20190820 06:03:51.365 TRACE grin_store::lmdb - Space remaining: 129753088
> 20190820 06:03:51.365 TRACE grin_store::lmdb - Percent used: 0.0333  Percent threshold: 0.9000
> 20190820 06:03:51.365 TRACE grin_store::lmdb - Resize threshold not met (percent-based)
> 20190820 06:03:51.370 INFO grin_wallet_impls - Using LMDB Backend for wallet
> 20190820 06:03:51.370 DEBUG grin_wallet_impls::seed - Using wallet seed file at: /root/.grin/main/wallet_data/wallet.seed
> 20190820 06:03:51.397 DEBUG grin_wallet_libwallet::internal::updater - Refreshing wallet outputs
> 20190820 06:03:52.180 TRACE grin_store::lmdb - DB map size: 134217728
> 20190820 06:03:52.180 TRACE grin_store::lmdb - Space used: 4464640
> 20190820 06:03:52.180 TRACE grin_store::lmdb - Space remaining: 129753088
> 20190820 06:03:52.180 TRACE grin_store::lmdb - Percent used: 0.0333  Percent threshold: 0.9000
> 20190820 06:03:52.180 TRACE grin_store::lmdb - Resize threshold not met (percent-based)
> 20190820 06:03:52.180 TRACE grin_store::lmdb - DB map size: 134217728
> 20190820 06:03:52.180 TRACE grin_store::lmdb - Space used: 4464640
> 20190820 06:03:52.180 TRACE grin_store::lmdb - Space remaining: 129753088
> 20190820 06:03:52.180 TRACE grin_store::lmdb - Percent used: 0.0333  Percent threshold: 0.9000
> 20190820 06:03:52.180 TRACE grin_store::lmdb - Resize threshold not met (percent-based)
> 20190820 06:03:52.191 TRACE grin_store::lmdb - DB map size: 134217728
> 20190820 06:03:52.191 TRACE grin_store::lmdb - Space used: 4464640
> 20190820 06:03:52.191 TRACE grin_store::lmdb - Space remaining: 129753088
> 20190820 06:03:52.191 TRACE grin_store::lmdb - Percent used: 0.0333  Percent threshold: 0.9000
> 20190820 06:03:52.191 TRACE grin_store::lmdb - Resize threshold not met (percent-based)
> 20190820 06:03:52.199 DEBUG grin_core::libtx::build - Building input (spending regular output): 273592986294, 03000000000000000000000a8600000000
> 20190820 06:03:52.199 DEBUG grin_wallet_libwallet::internal::selection - Building change outputs: total change: 264534562712 (1 outputs)
> 20190820 06:03:52.199 TRACE grin_store::lmdb - DB map size: 134217728
> 20190820 06:03:52.199 TRACE grin_store::lmdb - Space used: 4464640
> 20190820 06:03:52.199 TRACE grin_store::lmdb - Space remaining: 129753088
> 20190820 06:03:52.199 TRACE grin_store::lmdb - Percent used: 0.0333  Percent threshold: 0.9000
> 20190820 06:03:52.199 TRACE grin_store::lmdb - Resize threshold not met (percent-based)
> 20190820 06:03:52.199 TRACE grin_store::lmdb - DB map size: 134217728
> 20190820 06:03:52.199 TRACE grin_store::lmdb - Space used: 4464640
> 20190820 06:03:52.199 TRACE grin_store::lmdb - Space remaining: 129753088
> 20190820 06:03:52.199 TRACE grin_store::lmdb - Percent used: 0.0333  Percent threshold: 0.9000
> 20190820 06:03:52.199 TRACE grin_store::lmdb - Resize threshold not met (percent-based)
> 20190820 06:03:52.212 DEBUG grin_core::libtx::build - Building output: 264534562712, Commitment(08f59a8429d8839fbd9a9da328ae6e5f03ea6e127260fd9e8ed83222fa9d8a3c8c)
> 20190820 06:03:52.295 TRACE grin_store::lmdb - DB map size: 134217728
> 20190820 06:03:52.295 TRACE grin_store::lmdb - Space used: 4464640
> 20190820 06:03:52.295 TRACE grin_store::lmdb - Space remaining: 129753088
> 20190820 06:03:52.295 TRACE grin_store::lmdb - Percent used: 0.0333  Percent threshold: 0.9000
> 20190820 06:03:52.295 TRACE grin_store::lmdb - Resize threshold not met (percent-based)
> 20190820 06:03:52.300 INFO grin_wallet_controller::command - Tx created: 9.050423582 grin to https://grin.bitmesh.com/FTgXBDj5v8MtsQkrSc6Xi5e23 (strategy 'smallest')
> 20190820 06:03:52.300 DEBUG grin_wallet_impls::adapters::http - Posting transaction slate to https://grin.bitmesh.com/FTgXBDj5v8MtsQkrSc6Xi5e23/v2/foreign
> 20190820 06:03:53.415 TRACE grin_wallet_impls::adapters::http - Response: {"id":1,"jsonrpc":"2.0","result":{"Ok":{"foreign_api_version":2,"supported_slate_versions":["V2"]}}}
> 20190820 06:03:53.415 TRACE grin_wallet_impls::adapters::http - resp_value: {"foreign_api_version":2,"supported_slate_versions":["V2"]}
> 20190820 06:03:53.417 TRACE grin_wallet_impls::adapters::http - Sending receive_tx request: {"id":1,"jsonrpc":"2.0","method":"receive_tx","params":[{"amount":"9050423582","fee":"8000000","height":"310666","id"\
> :"17a4fc0d-712d-4e48-ab68-72821ef89031","lock_height":"0","num_participants":2,"participant_data":[{"id":"0","message":null,"message_sig":null,"part_sig":null,"public_blind_excess":"03b06b29cdacd213fce7b61d5ef\
> c4ad0c4a61d3fb969b0db6b7249450d74002365","public_nonce":"0329ce37d8289cbf0b95b379c9bf843707f167ec53c76273476418c06c3393710c"}],"tx":{"body":{"inputs":[{"commit":"095d97ce3dd461c5d4a4f6e44a70fa191b363bcacfe90f6\
> 0e2fb14cc90ac983d28","features":"Plain"}],"kernels":[{"excess":"000000000000000000000000000000000000000000000000000000000000000000","excess_sig":"000000000000000000000000000000000000000000000000000000000000000\
> 00000000000000000000000000000000000000000000000000000000000000000","features":"Plain","fee":"8000000","lock_height":"0"}],"outputs":[{"commit":"08f59a8429d8839fbd9a9da328ae6e5f03ea6e127260fd9e8ed83222fa9d8a3c8\
> c","features":"Plain","proof":"a711ace11a5f1eb4b0448ef32ab18c41ecb8b58b30fded279c9e583d28f782b2913a6bfb954257538bb26942b9d275a2d7ba5ba6580cec163da396377fafad3b071b338264a6c9c9cc41c50da6ab2a5fb3d3a9ff071c477865\
> fc59dbfb26c516fd2db64183e66eb37034c5c6a928d16d8710b284312d0248636065bd657a1a1edd130d6e52e3d20a52a62133a0552b4897ee88febe24ac915d8b726dc2e771593c2bb4e6a68481cedd275548f09bdcd1739f5303ed493b9d9e067f460e3061151ba\
> 79f92b09e080d1e41d956c02ef97295ca58c31f4e6d140d48175a5f1090e3a05037f95c181e82248392be5bc6601539de0c07f9b108f51528609ae3d0bc1f73bd490be1ff8b05d6f585e18e5ad45fa5fb55a265008a473f80553525026881affade84174198a70c90\
> e77fb9c0ae791212c8e9b68f32c1687d713518f17306387c63b8f7383a6ef1be604dcbe6ce099efcde3c3e626deccdb15026d01f3876984b01a453bdd8aa5cf4fb78a94c27e8dd196c23a0caa5c8c033753232e31033217555b83f3f38ee6215157ffe217f3ba83e1\
> ade353667f4027b23d03f1b6c86ad3deac1efb4a0cd32f92fde0317d26e7cd09954b0c98d7dfc3078c8586e30c67d1fb7cc644657ef34fdb1b2eef91463967538df7cea248624c938a7e27f83589a2242542f14344b31d96e6780e8049c989dece7d474dd6908b800\
> c8c611c150950394067a74b7609c011fb5ff7e433aa915b317ffc83e1e022fd330ac31c920868437ca591ee7f957d25b404155d4bd7bf08e035e2ffd3d6987d43c6f5424172f94dfdf22161b388bf48d8341c3c21bed2a7893a61cee3c6fb139898b59e9380db15c5\
> c506f1e8cff38d3bd713bcce1ba2ebf37f136ca4ef826925deba0cb60d7e15010a7e2c61848ac428c5bbaeba3e3dcaeca0519591ca00cfa05957dcb69eaa1f9"}]},"offset":"312079ad23cfe64636a9b0efaa06425516ab3408bb62b34042757ed4e9205ed2"},\
> "version_info":{"block_header_version":2,"orig_version":2,"version":2}},null,null]}
> 20190820 06:03:54.745 TRACE grin_wallet_impls::adapters::http - Response: {"error":"Not Found"}
> 20190820 06:03:54.745 ERROR grin_wallet_impls::adapters::http - Posting transaction slate: Error: null, Message: null

**Comment by yeastplume** [comment]
This was a small post-HF hiccup, shouldn't happen again.

**Comment by dyzz** [comment]
the receiver claims he's running a grin v2.0.0 node and works well for receiving before the error occurs.
