### ISSUE TITLE
help text for no argument

### ISSUE THREAD

**Issue by andylh66** [mimblewimble/grin-wallet#189]
If grin-wallet is invoked with no argument 
"Wallet command failed: Unknown wallet command, use 'grin help wallet' for details"
 is output to stdout

this should read 
"Wallet command failed: Unknown wallet command, use 'grin-wallet help' for details"

**Comment by yeastplume** [comment]
Slipped change into https://github.com/mimblewimble/grin-wallet/pull/211, thank you for pointing this out
