### ISSUE TITLE
after hard fork init_send_tx  "Err":"SlateDeser"

### ISSUE THREAD

**Issue by BeyongSpringWater** [mimblewimble/grin-wallet#190]
/v2/owner,
method=init_send_tx
data={"amount":1000000000,"minimum_confirmations":30,"num_change_outputs":1,"src_acct_name":null,"send_args":{"method":"http","finalize":true,"dest":"https://xxxxxxxx/api/grinApi","post_tx":false,"fluff":true},"target_slate_version":null,"max_outputs":1000,"selection_strategy_is_use_all":false}

the result of return:
{"id":"1","jsonrpc":"2.0","result":{"Err":"SlateDeser"}}

**Comment by BeyongSpringWater** [comment]
all of sender and reciever‘s grin wallet and grin server  version is v2.0.0

**Comment by quentinlesceller** [comment]
Also getting this when trying to http send from Grinmint to Kucoin.

**Comment by BeyongSpringWater** [comment]
> Also getting this when trying to http send from Grinmint to Kucoin.

include kucoin，bkex，hotbit，biforx, all meet this problem

**Comment by xiaojay** [comment]
Restart grin-wallet listener after hardfork seems fix this issue.
Maybe the exchange wallet didn't restart after hardfork

**Comment by BeyongSpringWater** [comment]
> Restart grin-wallet listener after hardfork seems fix this issue.
> Maybe the exchange wallet didn't restart after hardfork

thank you very much

**Comment by xiaojay** [comment]
mac and linux grin-wallet seems ok after restart.
however windows version still got this error: {"id":"1","jsonrpc":"2.0","result":{"Err":"SlateDeser"}}

**Comment by quentinlesceller** [comment]
Okay thanks @xiaojay ! Further tests made by @davidburkett show no issue with grin-wallet. Closing.
