### ISSUE TITLE
Enable secure connections between wallet and node

### ISSUE THREAD

**Issue by kargakis** [mimblewimble/grin-wallet#192]
Right now the http connection between the wallet and the node does not support TLS which means I cannot use a public node that I run in a different machine than my laptop without exposing my wallet connection. Sorry if this may be just a node API issue, feel free to move to mimblewimble/grin, if so.

**Comment by pinoli** [comment]
I just stumbled upon the same problem.
I can set my node to use TLS correctly, I checked it's working with Ironbelly on iOS through https.

But once I do it, **grin-wallet** can't find any node to connect to.
If I set `check_node_api_http_addr = "https://127.0.0.1:3413"` in **grin-wallet.toml** I get this error:
`ERROR grin_wallet_impls::node_clients::http - Unable to contact Node to get version info: Request error: Cannot make request: an error occurred trying to connect: invalid dnsname`

**Comment by mcdallas** [comment]
@kargakis I've been running a remote node behind nginx for my wallet forever and I connect to it with `grin-wallet -r https://my.remote.node info` without a problem. Or do you mean something else?

**Comment by kargakis** [comment]
@mcdallas you are right, I guess I can setup a reverse proxy

**Comment by mcdallas** [comment]
If you don't want to run a reverse proxy there is an option in grin-server.toml to provide a certificate (haven't tried it though)

```
#path of TLS certificate file, self-signed certificates are not supported
#tls_certificate_file = ""
#private key for the TLS certificate
#tls_certificate_key = ""
```
