### ISSUE TITLE
grin-wallet does not connect to local node when TLS is set in grin-server.toml

### ISSUE THREAD

**Issue by pinoli** [mimblewimble/grin-wallet#193]
Hello,
my current situation is:
1. `grin` and `grin-wallet` running on a hosted VM
2. `grin-wallet` set up with a TLS certificate, listening on 443 (to omit the port when giving the address)
3. Ironbelly on iOS setup with my own node and API secret

I have been using my https grin address with no issues for payouts and regular txs.
Now I noticed that TLS can be set up on the node as well, so I tried with the same certificate I used for the wallet. I did it because I wanted to use my own node with Ironbelly for iOS, mainly for testing, and I didn't want to settle for plain http. (Ironbelly connects just fine to my node through http)

But after setting `grin-server.toml` up with my TLS certificate, whenever I run any wallet command I get:
```
ERROR grin_wallet_impls::node_clients::http - Unable to contact Node to get version info: Request error: Cannot make request: parsed HTTP message from remote is incomplete
Password:
ERROR grin_wallet_impls::node_clients::http - Get chain height error: Request error: Cannot make request: parsed HTTP message from remote is incomplete
```

I troubleshooted the issue with @mcdallas but I could not solve it, and I thought opening an issue was the right way.
The only changes I made to my `grin-server.toml` were
```
#the address on which services will listen, e.g. Transaction Pool
api_http_addr = "0.0.0.0:3413"
```
and setting the two TLS paths, for file and key.

In this situation, Ironbelly connects just fine to the https node (through basic authentication with API secret), while `grin-wallet` installed on the same machine where the node runs, fails all the time with the above error. And if I comment the TLS settings, `grin-wallet` starts working again.

EDIT:
`grin` is built from source, latest `master` commit (09cf6de1).
`grin-wallet` is the 2.0.0 binary 

Thanks

**Comment by pinoli** [comment]
I can make it work if I set 
```
check_node_api_http_addr = "https://grin.mydomain.com:3413"
```
inside `grin-wallet.toml`, but if I use `https://127.0.0.1:3413` grin-wallet fails when TLS is enabled on the node.

Can anyone reproduce this issue?

**Comment by mcdallas** [comment]
That's normal. SSL certificates are bound to a domain name, you can't use a cert issued for "grin.mydomain.com" with localhost
