### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()`

### ISSUE THREAD

**Issue by GHLover** [mimblewimble/grin-wallet#195]
In windows this fatal error occurs:

grin_util::logger - 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 6, kind: Other, message: "The handle is invalid." }': src\libcore\result.rs:997stack backtrace:
   0: <no info> (0x7ff7ca4aa1ce)
   1: <no info> (0x7ff7ca4a8cb9)
   2: <no info> (0x7ff7ca459a11)
   3: <no info> (0x7ff7ca5654a5)
   4: <no info> (0x7ff7ca564fb4)
   5: <no info> (0x7ff7ca564e99)
   6: <no info> (0x7ff7ca57925c)
   7: <no info> (0x7ff7c9ed2851)
   8: <no info> (0x7ff7c9eadbc7)
   9: <no info> (0x7ff7c9ed788e)
  10: <no info> (0x7ff7c9f10d69)
  11: <no info> (0x7ff7c9f100f9)
  12: <no info> (0x7ff7c9f1e296)
  13: <no info> (0x7ff7ca564df7)
  14: <no info> (0x7ff7ca570982)
  15: <no info> (0x7ff7ca5656a2)
  16: <no info> (0x7ff7c9f11657)
  17: <no info> (0x7ff7ca5b8b5c)
  18: BaseThreadInitThunk (0x7ffe34ae84d4)
  19: RtlUserThreadStart (0x7ffe3511e851)

**Comment by yeastplume** [comment]
Could you provide more specific detail about the conditions under which this occurs? What command are you running, what's the wallet state, etc?

**Comment by yeastplume** [comment]
Closing due to lack of follow up.
