### ISSUE TITLE
Please provide 32bit binaries for Windows

### ISSUE THREAD

**Issue by GHLover** [mimblewimble/grin-wallet#197]
Windows binaries are generally 32bits and not 64bit. The platform indicates they are built for amd64 instead of being 32bit. Almost all software on windows is 32bit and every version of windows will run 32bit (and in fact is almost required for every bit of software even 64bit software because installers are almost exclusively 32bit in order to detect platform correctly).

There are many 32bit windows laptops and I think they should also be part of the grin community and not be excluded from it.

**Comment by quentinlesceller** [comment]
Here is the command that needs to be added to `azure-pipeline.yml`

```bash
rustup install stable-i686-pc-windows-gnu
cargo +stable-i686-pc-windows-gnu build
```

**Comment by yeastplume** [comment]
I don't believe this is as simple as setting a build flag. Grin has been aimed at 64-bit architectures from day 1 and there's a large stack of libraries and dependencies that need to be tweaked built, checked and verified for 32 bits. This work isn't going to be on my radar anytime soon, but it somebody wants to experiment with it it might be a good way to start getting familiar with Grin.

**Comment by yeastplume** [comment]
Going to close this as 'wontfix', as this is very non-trivial and not planned. If anyone still wants to pick this up by all means feel free
