### ISSUE TITLE
Owner API should leverage VersionedSlate and not Slate directly

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin-wallet#201]
Currently the Owner API uses `Slate` directly. This is too closely coupled to the internals of grin core. We should break this coupling and leverage `VersionedSlate`.

Are there any reasons _not_ to do this or why this would cause problems?

**Comment by yeastplume** [comment]
I don't know of a reason to not do this, am happy enough to make the change and test.

Can we hold off on this and #129 for a couple of days? The changes within https://github.com/mimblewimble/grin-wallet/pull/200 are a bit more pervasive than I thought originally, and I'd just like to get them in first before dealing with (and particularly testing) slate changes.
