### ISSUE TITLE
Easier authentication for third party services

### ISSUE THREAD

**Issue by mcdallas** [mimblewimble/grin-wallet#207]
Currently third party services need to use a url with a userid and a reverse proxy that handles that to authenticate users.

We could add a section with auth tokens for different services in the configuration file to make it easier to authenticate users.

```
[auth_tokens]
kucoin.com = "QDo7hybv4uKCIfof2Zc8"
mtgox.org= "Nopu6iv33mdTf1CqTQAc"
```
these can then be sent in the http request as a bearer token in the authentication header. We can also add it to the CLI as an argument i.e `grin-wallet send 20 -d https://wallet.exchange.com --auth_token xAbezqSejJHsQYRnYPhE`

**Comment by hashmap** [comment]
I’m not sure if it’s safe to store them in plain text. Also, tokens are supposed (I hope they are, but I don’t know) to be short-lived. The secure and easy to use scenario is smth like: a user does a multistep auth dance (including 2fa etc), as result a service generate an unique url with a short TTL (which is basically a token), a user uses it as the service’s wallet url.

**Comment by mcdallas** [comment]
It will be up to each service how often they want to rotate them. The `.api_secret` is stored in cleartext too. If your token is leaked it's the same as your deposit url being leaked i.e someone can deposit money/make a payment as you (not too big of a risk).

**Comment by yeastplume** [comment]
Perhaps this is worth looking at and picking up again? https://github.com/mimblewimble/grin-wallet/pull/186

**Comment by yeastplume** [comment]
Does anyone have further ideas on this given where we are today? I don't want to close this, but don't want to leave it hanging indefinitely either if nobody is going to pick it up.

**Comment by yeastplume** [comment]
Actually, this is probably better as an RFC (or part of a larger one) or further discussion in the wallet-dev channel if someone has further ideas on this, so will close for now
