### ISSUE TITLE
fatal error: 'stdbool.h' file not found

### ISSUE THREAD

**Issue by canndrew** [mimblewimble/grin-wallet#219]
I'm having trouble building grin wallet on Ubuntu. The dependency croaring-sys is failing to build with the error:

    CRoaring/roaring.h:37:10: fatal error: 'stdbool.h' file not found

Is there a native dependency missing? I have the build-essential and libclang-dev packages installed.

**Comment by knocte** [comment]
Just to provide more details: Andrew is referring to Ubuntu 18.04 (while CI on AzureDevOps seems to be using Ubuntu 16.04 at the moment).

**Comment by gnuletik** [comment]
I faced the same issue on Debian 10 (buster).
Googled it and find this related issue : https://github.com/carp-lang/Carp/issues/332
I tried to install clang
```bash
$ sudo apt install clang
```
Here are its dependencies:
```
The following additional packages will be installed:
  binfmt-support clang-7 libffi-dev libncurses-dev libomp-7-dev libomp5-7 libtinfo-dev llvm-7 llvm-7-dev llvm-7-runtime
```

and it fixed the build!
I guess one of the dependencies included stdbool.h
