### ISSUE TITLE
Documenting .owner_api_secret

### ISSUE THREAD

**Issue by michaeldzjap** [mimblewimble/grin-wallet#227]
I have just updated to v2.1.0-beta.1 for both wallet and node and I noticed I wasn't able to authenticate properly any more using the JSON RPC Api. For instance, using the call:

```
curl -v -u grin:`cat ~/.grin/floo/.api_secret` -d '{"jsonrpc": "2.0", "method": "retrieve_summary_info", "params": [true, 10], "id": 1}' -H "Content-Type: application/json" -H "Accept: application/json" -X POST http://127.0.0.1:3420/v2/owner
```

used to return a 200 response for me before (v2.0.0), but now results in a 401. After looking around a bit I noticed there now exists a _~/.grin/floo/.owner_api_secret_ file. Changing the call to:

```
curl -v -u grin:`cat ~/.grin/floo/.owner_api_secret` -d '{"jsonrpc": "2.0", "method": "retrieve_summary_info", "params": [true, 10], "id": 1}' -H "Content-Type: application/json" -H "Accept: application/json" -X POST http://127.0.0.1:3420/v2/owner
```

seems to fix things; I now get a 200 response again.

So it seems the way to authenticate with the owner Api has changed slightly, but I couldn't find documentation for this anywhere. In fact, the JSON RPC Api [guide](https://github.com/mimblewimble/docs/wiki/Wallet-JSON-RPC-API-Guide#transaction-query) only references `~/.grin/floo/.api_secret`.

**Comment by yeastplume** [comment]
The documentation for this change for the release notes is here: https://github.com/mimblewimble/grin-wallet/pull/218. We haven't 'officially' announced the beta yet (as we're going to be doing a beta.2 over the next day or so,) but that will be included in the changelog.

**Comment by yeastplume** [comment]
Docs are in release notes, so think we're okay here.
