### ISSUE TITLE
Add Payment Proofs

### ISSUE THREAD

**Issue by DavidBurkett** [mimblewimble/grin-wallet#230]
As part of the TOR tx building initiative, it would be great to include the ability to prove payments to a TOR address. @jaspervdm or I will create an RFC detailing how they should work. This is just a placeholder to make sure it's not forgotten.

**Comment by yeastplume** [comment]
#260, #266

**Comment by yeastplume** [comment]
Going to use this as the tracking issue, rfc is linked here: RFC - mimblewimble/grin-rfcs#31
