### ISSUE TITLE
Grin wallet on Windows

### ISSUE THREAD

**Issue by matso167** [mimblewimble/grin-wallet#238]
I see second time someone asking on forums how to run grin-wallet in Windows. People using Windows tend to expect programs to start by double clicking. So someone has to explain then to start cmd and run from there. So here I'm proposing two options:

a) Create a TUI for grin-wallet which can be started by double clicking under Windows
b) Include a README.txt in grin-wallet-vx.x.x-win-x64.zip with information how to run it with cmd

**Comment by kravens** [comment]
I like the idea of a TUI similar to the grin node!
If grin-wallet.exe is set to run in admin-mode, in Windows it will launch a separate terminal to run the command and closes again right after... only in an admin-console/terminal without the grin-wallet.exe itself in admin-mode can you see the output.

**Comment by yeastplume** [comment]
This is a good idea, but is unlikely to be picked up as part of core functionality. Would be great if you could add your thoughts to the packaging thread (and OS-specific packages are starting to appear!) https://github.com/mimblewimble/grin/issues/3093
