### ISSUE TITLE
request: check/restore/repair outputs from specific block number or timestamp

### ISSUE THREAD

**Issue by aleqx** [mimblewimble/grin-wallet#241]
The chain has grown and doing a wallet check now takes a little while (depends on the CPU as well). Would it be possible to add an option to check a wallet starting from a specific block number (as well as a timestamp, or relative time like `10d` for 10 days)? I admit I haven't yet read the tech details of Grin to know if this is possible in Grin as it is in Bitcoin or other protocols.

**Comment by hashmap** [comment]
Grin wallet doesn’t download all blocks, simply speaking it checks all unspent coins (utxo).

**Comment by aleqx** [comment]
I know it doesn't, but it starts checking from the first block all the time. I was asking about an option to start from a more recent block (like you can do in Monero for example)

**Comment by yeastplume** [comment]
Agreed, we're intending to rework how the wallet updates itself for 3.0.0, so this should be included

**Comment by lehnberg** [comment]
This issue will be resolved as part of https://github.com/mimblewimble/grin-wallet/issues/244

**Comment by yeastplume** [comment]
This is implemented in v3.0.0, see the description of `start_block_height` for `grin-wallet scan` in https://github.com/mimblewimble/grin-wallet/issues/262

**Comment by aleqx** [comment]
Nice to see this implemented. May I suggest a further and quick improvement? Allow negative values to signify the number of blocks in the past from the current height - similar to substr()-like functions, e.g. `scan -h -100` would scan from current height minus 100 onwards.
