### ISSUE TITLE
Hardcoded date?

### ISSUE THREAD

**Issue by davidtavarez** [mimblewimble/grin-wallet#245]
Why is this date hardcoded?

https://github.com/mimblewimble/grin-wallet/blob/b4eeb50c66302c7911026ded7bde6bc5fa22a818/impls/src/tor/process.rs#L233

**Comment by lehnberg** [comment]
The date itself is not of significance here. Looks like it is a sample timestamp that is used to define `timestamp_len`, by measuring the length of the string.

https://doc.rust-lang.org/std/string/struct.String.html#method.len
