### ISSUE TITLE
"data_dir" option has been broken

### ISSUE THREAD

**Issue by GHLover** [mimblewimble/grin-wallet#251]
The data_dir option in the grin-wallet command line has been broken. Instead of utilizing the supplied directory it will actually create it's own directory.

**Correct / old behavior:**
> grin-wallet --data_dir="/grin/" 

This will place a wallet.seed file inside of /grin/ along with creating sub-directories (db, etc)

**Buggy / current behavior:**
> grin-wallet --data_dir="/grin/" 

This will instead ignore the data_dir option and instead place everything inside of _/grin/wallet_data/_. It has created a different base directory than the one specified and different than previous behavior

**Comment by yeastplume** [comment]
Thanks for reporting, will have this fixed on master soon but the fix likely won't be released until 3.0.0

**Comment by yeastplume** [comment]
I'm going to leave this functionality as is, as the new wallet APIs all heavily rely on the concept of a `top_level_dir`, which contains the `grin-wallet.toml` file, which in turn specifies the location of the actual data dir. There should be no need to manually specify the location wallet data files without referencing the top level directory.

To alleviate the potential for confusion I'll rename the `data_dir` command line switch to `top_level_dir` for consistency with the APIs, but the behavior as currently exists is desired.
