### ISSUE TITLE
grin-wallet recover does not work

### ISSUE THREAD

**Issue by matso167** [mimblewimble/grin-wallet#256]
**$ grin-wallet --version**
grin-wallet 2.1.0
**$ grin-wallet init**
Please enter a password for your new wallet
Password: (press enter)
Confirm Password: (press enter)
WARN grin_wallet_impls::lifecycle::seed - Generating wallet seed file at: ...
Your recovery phrase is:
(recovery phrase)
Please back-up these words in a non-digital format.
Command 'init' completed successfully
**$ rm -rf .grin
$ grin-wallet recover**
ERROR grin_wallet_impls::node_clients::http - Unable to contact Node to get version info: Request error: Wrong response code: 401 Unauthorized with data Body
Please enter your recovery phrase:
phrase> (recovery phrase)
Password: (press enter)
Confirm Password: (press enter)
**Wallet command failed: LibWallet Error: Lifecycle Error: Error recovering from mnemonic**

**Comment by matso167** [comment]
Same problem when fully synced grin node is running.

**Comment by hendi** [comment]
I can confirm this, happens to me as well.

**Comment by hendi** [comment]
`trace` output:

```20191119 16:35:23.098 INFO grin_util::logger - log4rs is initialized, file level: Trace, stdout level: Warn, min. level: Trace
20191119 16:35:23.098 INFO grin_wallet - Using wallet configuration file at /home/hendi/.grin/main/grin-wallet.toml
20191119 16:35:23.098 INFO grin_wallet - This is Grin Wallet version 2.1.0 (git v2.1.0), built for x86_64-unknown-linux-gnu by rustc 1.38.0 (625451e37 2019-09-23).
20191119 16:35:23.098 DEBUG grin_wallet - Built with profile "release", features "".
20191119 16:35:23.107 DEBUG grin_wallet_impls::lifecycle::seed - Seed file path: test/wallet_data/wallet.seed
20191119 16:35:25.201 DEBUG grin_wallet_impls::lifecycle::seed - data file dir: test/wallet_data
20191119 16:35:25.201 DEBUG grin_wallet_impls::lifecycle::seed - Seed file path: test/wallet_data/wallet.seed
```

**Comment by yeastplume** [comment]
Does it work with `grin-wallet init -r` instead?

**Comment by hendi** [comment]
Yes, it does.

```20191119 16:39:05.036 INFO grin_wallet - This is Grin Wallet version 2.1.0 (git v2.1.0), built for x86_64-unknown-linux-gnu by rustc 1.38.0 (625451e37 2019-09-23).
20191119 16:39:05.036 DEBUG grin_wallet - Built with profile "release", features "".
20191119 16:39:10.471 INFO grin_wallet_impls::lifecycle::default - File test/grin-wallet.toml configured and created
20191119 16:39:10.471 DEBUG grin_wallet_impls::lifecycle::seed - Seed file path: test/wallet_data/wallet.seed
20191119 16:39:10.471 WARN grin_wallet_impls::lifecycle::seed - Generating wallet seed file at: test/wallet_data/wallet.seed
20191119 16:39:10.471 DEBUG grin_wallet_impls::lifecycle::seed - Seed file path: test/wallet_data/wallet.seed
20191119 16:39:10.472 INFO grin_wallet_impls::lifecycle::default - Wallet seed file created
20191119 16:39:10.472 DEBUG grin_store::lmdb - DB Mapsize for test/wallet_data/db/lmdb is 1048576
20191119 16:39:10.484 TRACE grin_store::lmdb - DB map size: 1048576
20191119 16:39:10.484 TRACE grin_store::lmdb - Space used: 8192
20191119 16:39:10.484 TRACE grin_store::lmdb - Space remaining: 1040384
20191119 16:39:10.484 TRACE grin_store::lmdb - Percent used: 0.0078  Percent threshold: 0.9000
20191119 16:39:10.484 TRACE grin_store::lmdb - Resize threshold met (percent-based)
20191119 16:39:10.484 INFO grin_store::lmdb - Resized database from 1048576 to 134217728
20191119 16:39:10.492 INFO grin_wallet_impls::lifecycle::default - Wallet database backend created at test/wallet_data
20191119 16:39:10.492 DEBUG grin_wallet_impls::lifecycle::seed - Using wallet seed file at: test/wallet_data/wallet.seed
```

**Comment by yeastplume** [comment]
Great, at least there's a workaround for now. I'm considering removing `recover` altogether 3.0.0 as it's redundant with `init -r`. With the progressive chain scanning in place 3.0.0 should perform an init, recover and restore (now called scan) in one `grin-wallet init -r` step

**Comment by kravens** [comment]
I've tried to recover too, the wallet will generate the files again with `grin-wallet init -r`, but it won't load the previous tx-data and shows a 0.00000 spendable balance... Running grin-node 2.1.1 on W10.

>PS C:\xxx> .\grin-wallet.exe check                                                                                                                                             Password: 20191126 20:02:21.466 WARN grin_wallet_controller::command - Starting wallet check...
20191126 20:02:21.467 WARN grin_wallet_controller::command - Updating all wallet outputs, please wait ...
20191126 20:02:21.477 WARN grin_wallet_libwallet::internal::restore - Starting wallet check.
20191126 20:02:21.483 ERROR grin_wallet_impls::node_clients::http - get_outputs_by_pmmr_index: error contacting http://127.0.0.1:3413. Error: ResponseError error: Cannot parse response
20191126 20:02:21.483 ERROR grin_wallet_controller::command - Wallet check failed: Restore Error
20191126 20:02:21.484 ERROR grin_wallet_controller::command - Backtrace:
Wallet command failed: LibWallet Error: Restore Error

**Comment by yeastplume** [comment]
`recover` only outputs the recovery phrase as of V3.0.0. Wallets can be recovered and restored with a single `grin-wallet init -r` command, meaning the very manual manipulations that needed to happen with the earlier `grin-wallet recover` are no longer needed and removed.
