### ISSUE TITLE
Cannot cancel by tx_id two times

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin-wallet#27]
Based on https://github.com/mimblewimble/grin/issues/2514 by @Onefox.

**Describe the bug**
If I receive a tx with ID 32222222-3222-4222-a222-322222222222 for example. Than I cancel that via `http://127.0.0.1:13420/v1/wallet/owner/cancel_tx?tx_id=32222222-3222-4222-a222-322222222222`

Now I receive another tx with that ID. 
I can't cancel the new one. When calling 
`http://127.0.0.1:13420/v1/wallet/owner/cancel_tx?tx_id=32222222-3222-4222-a222-322222222222`
I am getting 
`Transaction 32222222-3222-4222-a222-322222222222 doesn't exist`

1. Receive grin with ID `32222222-3222-4222-a222-322222222222`
2. Cancel that receive via `http://127.0.0.1:13420/v1/wallet/owner/cancel_tx?tx_id=32222222-3222-4222-a222-322222222222`
3. Receive the same tx again (for example with the listen api)
4. Try to Cancel that ID again...
5. See error `Transaction 32222222-3222-4222-a222-322222222222 doesn't exist`

Here is my txs wallet output:
![image](https://user-images.githubusercontent.com/1709259/52141706-d8ed8b00-2656-11e9-9736-347a8aeb178c.png)

 master tag V1.0.0

**Comment by yeastplume** [comment]
This is from 1.0.x, is this still an issue on the split 1.1.0?

**Comment by yeastplume** [comment]
Please reopen if still an issue in 2.0.0
