### ISSUE TITLE
Error wallet.seed and grin-wallet.toml exists when restoring from seed

### ISSUE THREAD

**Issue by hackinthebochs** [mimblewimble/grin-wallet#279]
When attempting to restore a wallet from mneumonic seed, the application first requests the seed, then requests a wallet password. Only after these are successfully entered does it check for the pre-existence of the wallet.seed and grin-wallet.toml files and exits with an error if they already exist. 

If you typed the wallet seed manually, this can be extremely frustrating to have to type it all again for an error the wallet could have checked for before the data was entered. This issue is also compounded by the fact that the file existence checks happen one at a time, which may require multiple attempts at creating the wallet including re-typing in the seed and wallet password.

**Comment by yeastplume** [comment]
Okay, valid point and worth looking into

**Comment by yeastplume** [comment]
Fixed via #318
