### ISSUE TITLE
how to use grin-wallet-3.0 rpc init_send_tx?

### ISSUE THREAD

**Issue by bxlkm1** [mimblewimble/grin-wallet#282]
node 2.0  and wallet2.0: 

curl -0 -XPOST --user grin:xxxxxxxxx -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"init_send_tx","params":{"args":{"src_acct_name":null,"amount":1000000000,"minimum_confirmations":10,"max_outputs":1,"num_change_outputs":1,"selection_strategy_is_use_all":true,"message":"i am verygood","target_slate_version":null,"send_args":{"method":"http","dest":"http://xxxxxx/NPgHguCqdAEsbZK","finalize":true,"post_tx":true,"fluff":false}}},"id":1}' http://127.0.0.1:3520/v2/owner
it's ok!!!  but v3.0 fail !!!

node : grin3.0
wallet: grin-wallet3.0
modify 2.0 to 3.0:(add payment_proof_recipient_address,ttl_blocks)
curl -0 -XPOST --user grin:xxxxxxx -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"init_send_tx","params":{"args":{"src_acct_name":null,"amount":1000000000,"minimum_confirmations":10,"max_outputs":1,"num_change_outputs":1,"selection_strategy_is_use_all":true,"message":"i am verygood","target_slate_version":null,"estimate_only":null,"payment_proof_recipient_address":null,"ttl_blocks":null,"send_args":{"method":"http","dest":"http://xxxxxx/NPgHguCqdAEtFNG","finalize":true,"post_tx":true,"fluff":false}}},"id":1}' http://127.0.0.1:3520/v3/owner

ret : 
{
  "error": {
    "code": -32001,
    "message": "Encryption must be enabled. Please call 'init_secure_api` first"
  },
  "id": 1,
  "jsonrpc": "2.0"
}

how to use v3?

**Comment by yeastplume** [comment]
Docs on how to use `init_secure_api` are available in rustdoc at https://docs.rs/grin_wallet_api/3.0.0/grin_wallet_api/trait.OwnerRpcS.html#tymethod.init_secure_api

There should be a user guide to demonstrate how to init and call the API from node.js, will open this as a separate issue.
