### ISSUE TITLE
Attempted to update via kernel excess for transaction Some(), but kernel excess was not stored

### ISSUE THREAD

**Issue by bitcodernull** [mimblewimble/grin-wallet#290]
WARN grin_wallet_libwallet::api_impl::owner - Attempted to update via kernel excess for transaction Some(), but kernel excess was not stored

 what happened? 
thanks

**Comment by yeastplume** [comment]
It likely means you have an outstanding transaction created prior to 2.1.0 that never finalized. Nothing to worry about, but you might want to cancel that transaction or just cancel all outstanding uncompleted transactions with `grin-wallet scan -d`

**Comment by bitcodernull** [comment]
thanks
