### ISSUE TITLE
grin-wallet-3.0 . grin_util::logger - thread 'tokio-runtime-worker-2' error

### ISSUE THREAD

**Issue by bitcodernull** [mimblewimble/grin-wallet#291]
`20200112 08:15:31.156 ERROR grin_util::logger -
thread 'tokio-runtime-worker-2' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }': src/libcore/result.rs:1165stack backtrace:
   0: grin_util::logger::send_panic_to_log::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   2: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
   3: rust_begin_unwind
             at src/libstd/panicking.rs:307
   4: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed
             at src/libcore/result.rs:1165
   6: futures_cpupool::Builder::create
   7: hyper::client::connect::dns::GaiResolver::new
   8: hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector>::new
   9: grin_wallet_impls::client_utils::client::Client::send_request_async
  10: grin_wallet_impls::client_utils::client::Client::send_request
  11: grin_wallet_impls::client_utils::client::Client::get
  12: <grin_wallet_impls::node_clients::http::HTTPNodeClient as grin_wallet_libwallet::types::NodeClient>::get_chain_tip
  13: grin_wallet_libwallet::api_impl::owner::node_height
  14: grin_wallet_api::owner::Owner<L,C,K>::node_height
  15: <grin_wallet_api::owner::Owner<L,C,K> as grin_wallet_api::owner_rpc::OwnerRpc>::node_height
  16: <dyn grin_wallet_api::owner_rpc::OwnerRpc as easy_jsonrpc_mw::Handler>::handle
  17: easy_jsonrpc_mw::handle_call
  18: easy_jsonrpc_mw::handle_parsed_request
  19: easy_jsonrpc_mw::Handler::handle_request
  20: <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll
  21: <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll
  22: <futures::future::or_else::OrElse<A,B,F> as futures::future::Future>::poll
  23: <hyper::proto::h1::dispatch::Server<S> as hyper::proto::h1::dispatch::Dispatch>::poll_msg
  24: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
  25: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  26: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as futures::future::Future>::poll
  27: <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as futures::future::Future>::poll
  28: futures::task_impl::std::set
  29: futures::task_impl::Spawn<T>::poll_future_notify
  30: std::panicking::try::do_call
  31: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  32: tokio_threadpool::task::Task::run
  33: tokio_threadpool::worker::Worker::run_task
  34: tokio_threadpool::worker::Worker::run
  35: tokio_reactor::with_default
  36: tokio::runtime::builder::Builder::build::{{closure}}
  37: std::thread::local::LocalKey<T>::with
  38: std::thread::local::LocalKey<T>::with
  39: std::sys_common::backtrace::__rust_begin_short_backtrace
  40: std::panicking::try::do_call
  41: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  42: core::ops::function::FnOnce::call_once{{vtable.shim}}
  43: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
  44: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  45: start_thread
  46: clone`

**Comment by yeastplume** [comment]
Looks like this error is coming from the OS, most likely running up against a user resource limit.

**Comment by bitcodernull** [comment]
i have not met the problem before i  upgraded to v3.0.0

**Comment by bitcodernull** [comment]
when wallet have the problem, the wallet stuck

**Comment by yeastplume** [comment]
This is 100% an OS resource limit issue, please feel free to ask for further help in the keybase grincoin#support channel
