### ISSUE TITLE
owner_api v3 "create_wallet" return "ok" even receive invalid mnemonic seeds.

### ISSUE THREAD

**Issue by xiaojay** [mimblewimble/grin-wallet#292]
Pass invalid seeds to owner_api v3 "create_wallet" still got ""result": {"Ok": null}" response.
Although wallet.seed does not created in fact.

maybe add validate mnemonic code in this line 
https://github.com/mimblewimble/grin-wallet/blob/45480392da42afee448fdabbfd4a29591be6c5ab/impls/src/lifecycle/default.rs#L186
?

**Comment by yeastplume** [comment]
Okay, thanks will look into this

**Comment by yeastplume** [comment]
Thanks for pointing this out, addressed in #319
