### ISSUE TITLE
"Unable to connect to node to get version info..."

### ISSUE THREAD

**Issue by Funkyswing** [mimblewimble/grin-wallet#300]
Hi there,

I can't open grin-wallet.exe. It tells that " ERROR grin_wallet_impls::node_clients::http - Unable to contact Node to get version info: Request error: Cannot make request: an error occurred trying to connect:" when I try to run. 

Could I ask what the problem is?

Thank you.

**Comment by quentinlesceller** [comment]
Hi @Funkyswing, do you have a node running on the same computer?

**Comment by Funkyswing** [comment]
Hi @quentinlesceller,

Thank you for answering. 

I haven't run a node. I want to connect with a remote node. Do I have to run a local node to run the client of wallet?

Thank you again.

**Comment by quentinlesceller** [comment]
You have to either:
- Run a node
- Specify the remote node IP:port in your config

**Comment by Funkyswing** [comment]
I can't run any command to secify a node. There is no configuration file (grin-wallet.toml) to do this as well. 

I think running a node is the only way. However, the node keeps shutdown in my end. It's weird.

**Comment by MCM-Mike** [comment]
@Funkyswing you could also for testing purposes use our public API nodes:
Details: https://github.com/MCM-Mike/grinnode.live

**how to use it:**
Change the following settings in your config

```
grin-wallet.toml :
          check_node_api_http_addr = "https://grinnode.live:3413"
```

**Comment by Funkyswing** [comment]
When I open the wallet, it keep asking for a password. I haven't initiated a wallet. What password can I use?

When I input any and press enter, the wallet cli shut down

**Comment by MCM-Mike** [comment]
@Funkyswing please check the documentation for how-to use the Grin wallet : https://github.com/mimblewimble/docs/wiki/How-to-use-the-Grin-wallet 

At the beginning it always asks for a password. You can set up a password or not. If you get a password promt just hit ENTER . But you should always use a password to protect your wallet

**Comment by yeastplume** [comment]
Closing, please refer to the user guide as listed above, or if you're still having issues feel free to ask on the keybase grincoin#support channel
