### ISSUE TITLE
'an IO error occurred: time out' when 'init_send_tx' called

### ISSUE THREAD

**Issue by xianggy** [mimblewimble/grin-wallet#304]
I use the rpc request `init_send_tx` to transfer grin, then get the error:
![image](https://user-images.githubusercontent.com/8045584/72708129-02236600-3b9d-11ea-9ced-fe7369054f59.png)

OS: CentOS 7 
version: grin3.0, grin-wallet3.0

What could be causing this? 

thank you.

**Comment by yeastplume** [comment]
It looks as if your node is not configured or running. There are some links to guides in this thread https://github.com/mimblewimble/grin-wallet/issues/300, or feel free to drop by the keybase grincoin#support channel
