### ISSUE TITLE
Switch node client to use Node v2 API

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin-wallet#305]
Swap the existing HTTP node client to use the Node's new JSON-RPC API instead of the V1 API. Should be relatively straightforward as the functionality is all in one file, but this will need to be tested thoroughly as none of the automated tests use the HTTP node client.

**Comment by quentinlesceller** [comment]
I can take this one :).

**Comment by yeastplume** [comment]
@quentinlesceller nice!
