### ISSUE TITLE
top_level_dir continues to broken 

### ISSUE THREAD

**Issue by GHLover** [mimblewimble/grin-wallet#308]
--top_level_dir continues to be broken and has not really worked since I reported an issue when it was named data_dir in the last versions of grin.

**What is the Issue?**
--top_level_dir does NOT load the grin-wallet.toml that was defined in the custom directory. Grin will correctly make the grin-wallet.toml in that directory if it does not exist. It will even set all the paths correctly for the api secrets and logging in said generated grin-wallet.toml.

However, it does NOT load the configuration file and utilize it as part of it's configuration and therefore it is impossible to run with a custom config path.

**Reproducing The Issue**
This can be verified running these two commands (notice the ".grin2" and not ".grin"):

1) grin -t /home/user/.grin2/ init
2) grin -t /home/user/.grin2/ info

When (1) is run it will create a wallet_data and grin-wallet.toml file as expected in /home/user/.grin2/. If you look at the grin-wallet.toml file you will see all config options have correctly set paths to /home/user/.grin2/ for everything from the api_secret to the wallet logging.

However, you will notice when running (1) or (2) that grin continues to ignore /home/user/.grin2/grin-wallet.toml. Instead, it will create files in /home/user/.grin/. Running the wallet command will fill the incorrect log path /home/user/.grin/main/grin-wallet.log with information.

This should ALL be put inside of /home/user/.grin2/ and the log should be at /home/user/.grin2/grin-wallet.log. This is where it is defined to be at via the "log_file_path" that grin auto-created when it auto-greated the grin-wallet.toml.

**Comment by yeastplume** [comment]
Okay, thanks for the detailed description, will look into it before next release
