### ISSUE TITLE
scan from relative block to current height

### ISSUE THREAD

**Issue by aleqx** [mimblewimble/grin-wallet#320]
Further to my suggestion #241 (many thanks for implementing that!) may I suggest a further and quick improvement? Allow negative values to signify the number of blocks in the past from the current height - similar to substr()-like functions, e.g. `scan -h -100` would scan from current height minus 100 onwards.

**Comment by yeastplume** [comment]
Yep, sounds worthwhile, thanks for the suggestion

**Comment by yeastplume** [comment]
Addressed in #325
