### ISSUE TITLE
did any one know how to solved it

### ISSUE THREAD

**Issue by Aleksander12356** [mimblewimble/grin-wallet#322]
20200203 23:59:52.826 ERROR grin_wallet_impls::node_clients::http - Unable to contact Node to get version info: ResponseError error: Cannot parse response
Password:

i can't go through this i'm not an IT specialist and i don't know how to solve it

**Comment by yeastplume** [comment]
Hi, it's difficult to tell what the issue might be from the information given, but you're still having the issue please feel free to stop by the gitter support channel.. some there should be able to help you
