### ISSUE TITLE
init_secure_api always fail,how use it

### ISSUE THREAD

**Issue by OnfireMrHuang** [mimblewimble/grin-wallet#328]
node: v3
method:init_secure_tx
I generate key pairs
secp256k1
private key: 115474345373139562295826270636271299467049365661696312047764741708410397887674
public key:   cf4ea054198ff209d74f37607fd1a42b2a74698b3a77f728ef31a349ca5cacda

and 

curl -v -X POST -d '{"jsonrpc": "2.0","method":"init_secure_api","params":{"ecdh_pubkey":"cf4ea054198ff209d74f37607fd1a42b2a74698b3a77f728ef31a349ca5cacda"},"id":1}' 'http://grin:xxxxxxx@127.0.0.1:3420/v3/owner'

always reponse

{
  "error": {
    "code": -32602,
    "message": "InvalidArgStructure \"ecdh_pubkey\" at position 0."
  },
  "id": 1,
  "jsonrpc": "2.0"
* Connection #0 to host 127.0.0.1 left intact
}

why?

**Comment by yeastplume** [comment]
There is now [sample node code](https://github.com/mimblewimble/grin-wallet/tree/master/doc/samples/v3_api_node) in the project that demonstrates how to connect. I can definitely guarantee `init_secure_api` works there, at least.

Were you able to find the issue? Otherwise looking at the sample might help

**Comment by xiaojay** [comment]
wrong public key, it's length shoud be 66.
node code for this:
https://github.com/grinfans/Niffler/blob/gw3/src/shared/walletv3.js#L110

**Comment by yeastplume** [comment]
This is confirmed working, and there are two sets of sample code attached. If you're still having this issue, please feel free to stop by the support channel and someone will be able to help you
