### ISSUE TITLE
ERROR grin_wallet_impls::adapters::http - Performing version check (is recipient listening?): Request error: Cannot make request: channel closed

### ISSUE THREAD

**Issue by yangchunhe** [mimblewimble/grin-wallet#349]
version:grin-wallet 3.1.0-beta.2
when I send coin by http,the error:
./grin-wallet send -d https://abc.xx.com/grin/v1/111 1

20200228 13:39:48.577 ERROR grin_wallet_impls::adapters::http - Performing version check (is recipient listening?): Request error: Cannot make request: operation was canceled: received unexpected message from connection
Wallet command failed: LibWallet Error: Client Callback Error: Performing version check (is recipient listening?): Request error: Cannot make request: operation was canceled: received unexpected message from connection

**Comment by jaspervdm** [comment]
Fixed in v3.1.1
