### ISSUE TITLE
Grin wallet owner api wont confirm tx

### ISSUE THREAD

**Issue by Jlonghi** [mimblewimble/grin-wallet#36]
I’m trying to use the grin wallet owner api in an app i’m developing.

When I send grin I first make a call to `/v1/wallet/owner/issue_send_tx`
Then I repost the tx-id with `v1/wallet/owner/repost?tx_id=`

The issue im running into is the tx does not become confirmed until I manually go to my grin wallet and run grin wallet txs. As soon as I run that command the tx gets confirmed. Should I switch to using
`v1/wallet/owner/post`?

On the owner api the logs show that the tx is created succesfully:
```
20190401 21:02:46.276 DEBUG grin_wallet::libwallet::internal::selection - Building change outputs: total change: 26434382076 (2 outputs)
20190401 21:02:46.305 DEBUG grin_core::libtx::build - Building output: 13217191038, Commitment(xxx)
20190401 21:02:46.362 DEBUG grin_core::libtx::build - Building output: 13217191038, Commitment(xxx)
20190401 21:02:46.455 INFO grin_wallet::controller - Tx created: 4.002346725 grin to http://x.x.x.x:3415 (strategy 'false')
20190401 21:02:46.455 DEBUG grin_wallet::adapters::http - Posting transaction slate to http://x.x.x.x:3415/v1/wallet/foreign/receive_tx
```

**Comment by yeastplume** [comment]
The wallet currently doesn't update its outputs until the next info or txs command, this is by design at the moment.

**Comment by Jlonghi** [comment]
Ok thanks for responding. Thats a bit annoying when trying to find if a tx is confirmed via the wallet owner api. The fix would be to programatically run those commands for now but thats not ideal.
