### ISSUE TITLE
"./grin-wallet info"  spend long time

### ISSUE THREAD

**Issue by OnfireMrHuang** [mimblewimble/grin-wallet#369]
![image](https://user-images.githubusercontent.com/22336719/77315628-d5c5ca80-6d42-11ea-8d3d-c77372f0863f.png)

system:  ubuntu16
memory: 2G
disk:  150G

grin-wallet: 3.1.1
grin: 3.0.0

**Comment by MCM-Mike** [comment]
Could be your node, which was not fast enough.
Are you getting this values all the time?

You can try it with a remote node if its faster to compare against your numbers:
`_$ time ./grin-wallet --api_server_address "https://grinnode.live:3413" info`

_(Details https://github.com/MCM-Mike/grinnode.live/blob/master/linux-grin-commands-collection.md#use-grin-wallet-without-own-grin-node)_
