### ISSUE TITLE
sending GRIN across local top_level_dir

### ISSUE THREAD

**Issue by MCM-Mike** [mimblewimble/grin-wallet#376]
In some situations like

- transferring into offline storage 
- transferring GRIN amount to different server 
- sometimes its not possible to run _HTTP/TOR listener_ on internal servers which don't have a direct Internet connection 

it would be helpful if Grin-Wallet would support a ```top_level_dir``` to ```top_level_dir``` local transfer. Without having the ```listener``` on in order to receive or transfer local funds. 

**Example:** 

`_$ grin-wallet --top_level_dir /opt/grin/wallets/1 --account someAccount send -m **self** -d /opt/grin/wallet/2  X`

It would also be great to set a account on the receiving wallet.

**Comment by jaspervdm** [comment]
You can send between local wallets using the file method, which doesn't require you to run a http or tor listener.

**Comment by MCM-Mike** [comment]
I think we can close this request because there is an existing one which more or less is about to implement what I suggested:

- https://github.com/mimblewimble/grin-rfcs/pull/12

- https://github.com/mimblewimble/grin-rfcs/pull/12/commits/304ca7612a32bebcc904e2f75cfc34af0642d0b0
