### ISSUE TITLE
Grin payments to ipv6 addresses

### ISSUE THREAD

**Issue by kargakis** [mimblewimble/grin-wallet#38]
There have been a couple of requests for ipv6 support in the forum ([latest](https://www.grin-forum.org/t/how-to-withdrawal-from-hotbit-to-grin-wallet/4756/9)). Apparently, the grin node supports syncing over ipv6 at the p2p layer, but it's unclear whether paying to an ipv6 address works.

According to [RFC2732](https://www.ietf.org/rfc/rfc2732.txt), the following format is a valid one for http:
```
http://[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]:80
```
where the ipv6 address is enclosed in square brackets. So the grin wallet should be able to support ipv6 payments:
```
grin wallet send -d http://[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]:3415 10
```
Hyper seems to support ipv6 so it may simply be an issue of adding a test case in the wallet to prove that ipv6 addresses work?

**Comment by MCM-Mike** [comment]
@kargakis I think we can close this issue now as we cant send to IPv6 anymore.

**Comment by quentinlesceller** [comment]
Indeed closing.
