### ISSUE TITLE
Improve Offset Selection

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-wallet#405]
Ensure 4.0.0 offset selection is future-compatible with [lock-free transactions](https://forum.grin.mw/t/mostly-lock-free-transactions/7313/), to test the idea ahead of v5.0.0. 

It means:
* to standardize on when the offset is chosen; and
* to ensure the offset isn't applied to anyone's blinding factors as it currently is, and is passed around explicitly.

**Comment by lehnberg** [comment]
https://github.com/mimblewimble/grin-wallet/pull/407

**Comment by yeastplume** [comment]
Handled in 4.0.0
