### ISSUE TITLE
4.0.0-beta.1 ignores filename when saving slatepack

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin-wallet#429]
Expected send "-d send.tx" would save the slate file to ./send.tx but instead it is saved to /home/grin/.grin/main/slatepack/85b8f74a-fe0a-42f4-9757-cbbeae1a7a10.S1.slatepack

```
grin@crypto:~$ grin-wallet send -d send.tx 1
Password:

Transaction file was output to:

/home/grin/.grin/main/slatepack/85b8f74a-fe0a-42f4-9757-cbbeae1a7a10.S1.slatepack

Please send this file to the other party manually
Command 'send' completed successfully
```

**Comment by quentinlesceller** [comment]
Reading the RFC again It's unclear whether or not  this be user defined or not.

**Comment by yeastplume** [comment]
This is handled now in 4.0.0 with the `--outfile` flag
