### ISSUE TITLE
Error parsing create_slatepack_message Owner API from javascript

### ISSUE THREAD

**Issue by fungibly** [mimblewimble/grin-wallet#438]
Calling the new `create_slatepack_message` owner api results in:
```
{"id":"1","jsonrpc":"2.0","result":{"Ok":"BEGINSLATEPACK. BikBVY4UhC3Nnj4 ... gYgYXNX. ENDSLATEPACK.\n"}}
```
The trailing "\n" breaks `JSON.parse()`, can it either be escaped "\\\\n" or omitted instead?

**Comment by yeastplume** [comment]
Thank you for testing and reporting, fix is in #444 and should be available as of beta.3
