### ISSUE TITLE
SlatepackWorkflow: (deliberately) skipping Tor

### ISSUE THREAD

**Issue by davidtavarez** [mimblewimble/grin-wallet#451]
We're on our way to have an unified workflow, which is good, but I think that Senders should be able to intentionally skip Tor while starting a Transaction. Currently the [Slatepackworkflow ](https://github.com/j01tz/grin-rfcs/blob/slatepack/text/0000-slatepack.md#slatepackworkflow) reads like this:

```
3.- (Fallback) If the synchronous transaction fails, a SlatepackMessage string is encrypted
to the SlatepackAddress and output for manual asynchronous transport by the user
```

This period could last between 20 to 30 seconds and sometimes I just know that the receiver is not online, but anyways there is no reason to limit users to this flow.

Let's put this example: I sell ice cream and I accept grins... so, even though I could be online most of the time. I want to save a few seconds on every purchase, but also **I want to rely on a stable method to receive grins**. The interaction could be like this: the Sender scan my `SlatepackAddress` with his mobile app and then the exchange happens via NFC.

The Sender could just enable a NFC switch.
![sender](https://user-images.githubusercontent.com/337107/84877398-bf50b600-b088-11ea-8334-5cf63c59d77c.png)

The Receiver is always "listening".
![wallet](https://user-images.githubusercontent.com/337107/84878542-42264080-b08a-11ea-990d-7a5534caf00d.png)

Potential Flow # 1: Sender enable the NFC and then scan the QR. Everything happens "magically".
Potential Flow # 2: Sender enable the NFC and brings close his/her mobile to the Receiver mobile. Everything happens "magically".

I suggest to add a flag like `--offline` like this:

```
$ grin-wallet send -d XYZ 1.337 --offline
```
or
```
$ grin-wallet send 1.337 --offline
```

This flexibility could facilitate the UX from a mobile perspective.

**Comment by lehnberg** [comment]
I'm :+1: on the motivation, i.e. having some flag that instructs the wallet to output the slate as a slatepack text blob directly, even if an address has been provided. You might still share the blob through online means though, even if it's not via Tor. Perhaps `--manual` is a better description?

**Comment by yeastplume** [comment]
Yes, this makes sense, and shouldn't be too intrusive so will add this to the next beta or RC.

**Comment by yeastplume** [comment]
Handled via #453
