### ISSUE TITLE
invalid shasum

### ISSUE THREAD

**Issue by jesseposner** [mimblewimble/grin-wallet#465]
anyone else having trouble verifying the shasum for grin-wallet-v4.0.0-macos.tar.gz?

The shasum [file](https://github.com/mimblewimble/grin-wallet/releases/download/v4.0.0/grin-wallet-v4.0.0-macos-sha256sum.txt):
```
SHA256(/Users/runner/runners/2.171.1/work/1/a/grin-wallet-v4.0.0-macos.tar.gz)= f18615b8f2d49bf444fd0f413a322984e5fb36147cc0031f637b86ee17d82d15
```
however:
```
$ wget https://github.com/mimblewimble/grin/releases/download/v4.0.0/grin-v4.0.0-macos.tar.gz
$ shasum -a 256 grin-v4.0.0-macos.tar.gz
dad23536f02a983ab0feb7d7c66e51026a043db193f9d580e842d6ac39a1645f  grin-v4.0.0-macos.tar.gz
```

**Comment by lehnberg** [comment]
Hi @jesseposner, thanks for filing an issue! 

It looks like you're trying to verify the shasum for _grin-wallet_ using the _grin_ node binary.
The shasum you linked above is for the wallet, and the [shasum for the node](https://github.com/mimblewimble/grin/releases/download/v4.0.0/grin-v4.0.0-macos-sha256sum.txt) is the one you produced.

```
~/dev $ shasum -a 256 grin-v4.0.0-macos.tar.gz \
        shasum -a 256 grin-wallet-v4.0.0-macos.tar.gz
dad23536f02a983ab0feb7d7c66e51026a043db193f9d580e842d6ac39a1645f  grin-v4.0.0-macos.tar.gz
shasum: shasum: 
f18615b8f2d49bf444fd0f413a322984e5fb36147cc0031f637b86ee17d82d15  grin-wallet-v4.0.0-macos.tar.gz
```

**Comment by jesseposner** [comment]
you are right, it checks out now:
```
$ shasum -a 256 grin-wallet-v4.0.0-macos.tar.gz
f18615b8f2d49bf444fd0f413a322984e5fb36147cc0031f637b86ee17d82d15  grin-wallet-v4.0.0-macos.tar.gz
```

Thanks!
