### ISSUE TITLE
where can i found the document of wallet v4.0.0 ?

### ISSUE THREAD

**Issue by olizax** [mimblewimble/grin-wallet#481]
The document  [Wallet JSON RPC API Guide](https://github.com/mimblewimble/docs/wiki/Wallet-JSON-RPC-API-Guide#wallet-summary-query) has not been updated for more than a year.

Every major version modifies the API, but does not provide API documentation. What do you think?

**Comment by quentinlesceller** [comment]
Hi @olizax, I agree with you that there is a lot of outdated doc. We are working on it.
The developer documentation here https://docs.rs/grin_wallet_api/4.0.0/grin_wallet_api/ is always up to date.
