### ISSUE TITLE
how to build grin-wallet v4.0.0 for ubuntu 16.04

### ISSUE THREAD

**Issue by Alteryy** [mimblewimble/grin-wallet#482]
how to or where is docs

**Comment by Alteryy** [comment]
is anybody here?

**Comment by quentinlesceller** [comment]
Hello, we are working on a new user friendly documentation.
For now install install rust with rustup https://rustup.rs
Clone the project.
Run `cargo build --release`.

**Comment by Alteryy** [comment]
error: attributes are not yet allowed on `if` expressions
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/sysinfo-0.14.5/src/utils.rs:27:5
   |
27 |     #[allow(clippy::identity_conversion)]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `sysinfo`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by quentinlesceller** [comment]
Which version of rust are you using?
