### ISSUE TITLE
retrieve_outputs not working when tx_id not null

### ISSUE THREAD

**Issue by omgfin** [mimblewimble/grin-wallet#484]
Dear team, 
We have an issue when running wallet-api v4.0.0

Run at mainnet
API: https://docs.rs/grin_wallet_api/4.0.0/grin_wallet_api/trait.OwnerRpc.html#tymethod.retrieve_outputs

{
	"jsonrpc": "2.0",
	"method": "retrieve_outputs",
	"params": {
		"token": "token here",
		"include_spent": false,
		"refresh_from_node": true,
		"tx_id": "tx id value"
	},
	"id": 1
}

error responding:

{ error:
   { code: -32602,
     message: 'InvalidArgStructure "tx_id" at position 3.' },
  id: 1595233907,
  jsonrpc: '2.0' }

if tx_id is null, the API works well.

Please address the issue,
Thanks

**Comment by yeastplume** [comment]
What's the actual value of the txid you've inserted? It should be a u32 corresponding to the wallet's transaction log id, not the slate UUID

**Comment by omgfin** [comment]
It's working.

Thank you so much.
