### ISSUE TITLE
Account info in CLI mode

### ISSUE THREAD

**Issue by mojitoo** [mimblewimble/grin-wallet#488]
in CLI mode, `info` command keeps showing Default account summary instead of the opened account

____ Wallet Summary Info - Account '**default**' as of height xxx ____

To check the address of a specific account after opening it, you will get the right address but will display

Address for account - **default**

`-a accountx address` will display the current opened account with Address for account - **default**

**Comment by Paouky** [comment]
Do you still have that problem?

Because I can't reproduce it,
