### ISSUE TITLE
waiting for peers

### ISSUE THREAD

**Issue by rcmartinsmso** [mimblewimble/grin-wallet#489]
I am unable to transfer funds out of the wallet. It says waiting for peers. I've restarted the wallet several times and re synced the nodes but that didn't solve the issue.

**Comment by quentinlesceller** [comment]
Can you try again now?

**Comment by rcmartinsmso** [comment]
I am away from my computer but can try this afternoon when I get home. 
 
 
 
-----Original Message-----

**Comment by rcmartinsmso** [comment]
It's still showing waiting for Peers. I restarted it twice and it hasn't tried to re sync. I also tried the resync button in options.

**Comment by quentinlesceller** [comment]
Which version of grin are you using ?

**Comment by rcmartinsmso** [comment]
v1.0.6

**Comment by quentinlesceller** [comment]
Are you using Grin or Grin++?

**Comment by rcmartinsmso** [comment]
yes

**Comment by yeastplume** [comment]
We don't provide Grin++, you might have better results filing an issue on the Grin++ repository
