### ISSUE TITLE
introduce progress indicator for `grin wallet restore`

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-wallet#49]
Currently, `grin wallet restore` progress is bit of a mystery for the user. No indication of how long it takes to complete a restore, nor whether the wallet is actually working on something or not.

It would be useful to see some kind of progress indicator, even the most rudimentary version, to indicate that the restore process is not just stuck somewhere.

**Comment by yeastplume** [comment]
You have your wish, and this is included in v3.0.0 via the API and via an MPSC queue if you're linking directly!
