### ISSUE TITLE
 ubuntu 16.04 build error:could not compile `sysinfo`

### ISSUE THREAD

**Issue by Alteryy** [mimblewimble/grin-wallet#491]
Hello, we are working on a new user friendly documentation.
For now install install rust with rustup https://rustup.rs
Clone the project.
Run `cargo build --release`.

_Originally posted by @quentinlesceller in https://github.com/mimblewimble/grin-wallet/issues/482#issuecomment-661046932_

error: attributes are not yet allowed on `if` expressions
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/sysinfo-0.14.5/src/utils.rs:27:5
   |
27 |     #[allow(clippy::identity_conversion)]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `sysinfo`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by quentinlesceller** [comment]
Can you post the full error ?
