### ISSUE TITLE
grin-wallet owner_api can not start without a wallet config

### ISSUE THREAD

**Issue by xiaojay** [mimblewimble/grin-wallet#492]
We need use owner_api 'create_config' and 'create_wallet' to recover wallet

however grin-wallet owner_api can not start without a wallet config.
the error info is
"""
grin4 % ./grin-wallet owner_api
Wallet configuration not found at /Users/jay/.grin/main. (Run `grin-wallet init` to create a new wallet)
"""

**Comment by yeastplume** [comment]
I've just checked with 4.0 and current master, `grin-wallet --floonet owner_api` starts up for me without issue anyhow. Could you try with the master branch just to be sure?

**Comment by xiaojay** [comment]
On a fresh mac system, without ~/.grin/main dir.
then run command:

./grin-wallet owner_api 

will produce error:

Wallet configuration not found at /Users/yuanjieyang/.grin/main. (Run `grin-wallet init` to create a new wallet)

ok, it's not a big issue. 
In niffler wallet, I just create dir ~/.grin/main  first, then start owner_api.
