### ISSUE TITLE
Current Wallet API Doesn't Allow Merchants to Differentiate Payers

### ISSUE THREAD

**Issue by overlooper** [mimblewimble/grin-wallet#50]
If a merchant were to programmatically implement an application that takes Grin deposits, as of right now there is no variable that can be parsed in the [wallet owner API](https://github.com/mimblewimble/grin/blob/master/doc/api/wallet_owner_api.md#get-retrieve-txs) that would allow the merchant to differentiate a deposit of one payer from another payer's if they deposit the same amount at roughly the same time.

Monero had initially solved this problem with payment IDs that a merchant would provide to the payer before a transaction for them to specify during the transaction in a separate field. This turned out to be a terrible solution that not only compromised privacy at the network level but also created a UX nightmare, where exchanges would ask people to attach a certain payment ID to their transaction, the payers then not doing it due to inexperience or negligence, and the merchants having to sift through the transactions manually to find the payment, resulting in enormous productivity losses all around, users losing their funds due to merchants being unwilling to go through the hassle and a terrible experience for all involved, creating a perception for newcomers that this currency is hard to use and easy to lose.

After Monero had implemented integrated addresses, where the payment ID was baked into the address that the merchants provided to their users for deposits this UX issue was solved at the protocol level, but for years merchants kept using old-style payment IDs, opting to charge their users for finding missing transactions rather than implement the new integrated addresses. Due to backwards compatibility, this problem is [still plaguing Monero even to this day](https://github.com/monero-project/monero/issues/3772).

This is why, in the case of Grin, telling the payer to add a message to the transaction with their merchant portal username is a terrible solution, in my opinion.

The ideal solution, in my view, would be a field (let's call it payer-id) that could be specified or saved by the receiver during their stage of the transaction creation, and that the receiver can later parse from a field in the [retrieve_txs](https://github.com/mimblewimble/grin/blob/master/doc/api/wallet_owner_api.md#get-retrieve-txs) method of the owner wallet API when the transaction gets added to the blockchain (note, this does not necessarily have to be something that is stored on the blockchain, it could be a transaction-specific property that can be associated to a payer-id at the wallet level). This way a merchant would be able to link together all the deposits received from a given user due to that user being provided the same payer-id by the merchant's platform, just like when a payer is given the same integrated address to deposit to in Monero, allowing the merchant to easily scan all transactions from a given payer.

I don't know whether this kind of solution is possible for a MW blockchain, so, in case it isn't, I just want to emphasize that the main requirements for this solution are as follows:

1. It has to require ZERO extra actions from the payer, all the differentiation logic should be done by the merchant.
2. It has to either be something the merchant can specify OR something that a merchant can save before or during a transaction creation that is unique to this transaction or payer, that will be later
3. something that the merchant can retrieve during the scanning of an incoming transaction from the blockchain. I.e. a field in the [retrieve_txs](https://github.com/mimblewimble/grin/blob/master/doc/api/wallet_owner_api.md#get-retrieve-txs) method of the owner wallet API.

I also believe this should be prioritized to be implemented before the mainnet launch so as to allow merchants to prepare for launch and, more crucially, avoid transaction uniformity issues in the future (e.g. in Monero the transactions that have a payment ID can have a fingerprint different from the ones that don't).

**Comment by yeastplume** [comment]
This discussion is covered by a few other issues, closing this in favour of them.
