### ISSUE TITLE
Support Apple Silicon

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin-wallet#571]
Equivalent of https://github.com/mimblewimble/grin/issues/3545 for grin-wallet.
Currently Grin-Wallet does not build on Apple Silicon (ARM M1). For two reasons:
- Ring must be updated to >="0.16.16". Easy fix with `cargo update -p ring`.
- croaring-rs (in fact croaring-sys does not compile for an unknown reason. See https://github.com/saulius/croaring-rs/issues/66. EDIT: Fixed by https://github.com/saulius/croaring-rs/pull/67. Wondering if we still need that fork of croaring btw.

**Comment by trevyn** [comment]
Ran the `grin-wallet` dual of https://github.com/mimblewimble/grin/issues/3545#issuecomment-801916537 on `aarch64-apple-darwin` as such:

```
git clone -b trevyn-croaring-defork https://github.com/trevyn/grin-wallet.git
cd grin-wallet
cargo update -p ring
cargo build
cargo build --release
cargo test --all
```

All worked on:

```
rustc 1.50.0 (cb75ad5db 2021-02-10)
rustc 1.51.0-beta.7 (80eddb935 2021-03-17)
rustc 1.52.0-nightly (36f1f04f1 2021-03-17)
```

Will submit PR when https://github.com/mimblewimble/grin/pull/3596 is merged.

**Comment by quentinlesceller** [comment]
We now support Apple Silicon! Thanks @trevyn
