### ISSUE TITLE
how to generate an unique Slatepack Address for different users

### ISSUE THREAD

**Issue by xianggy** [mimblewimble/grin-wallet#579]
I'm wallet developer and I encountered a situation:
How to generate an independent Slatepack address for each user, so that I can distinguish who made that transfer when someone send some GRINs?
Thanks.

**Comment by j01tz** [comment]
https://github.com/mimblewimble/grin-wallet/blob/master/api/src/owner.rs#L1941
To generate new slatepack addresses, you can iterate through the indexes on the derivation path designated for slatepack addresses.

**Comment by cliik** [comment]
Can this issue be closed? Looks like the original question was adequately answered.

**Comment by xianggy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by phyro** [comment]
Agree, closing.
