### ISSUE TITLE
Make The CLI Optional

### ISSUE THREAD

**Issue by gringineer** [mimblewimble/grin-wallet#583]
[While I was writing this guide...](https://github.com/gringineer/gringineer/blob/main/README.md)

I found out that you can't go from start to finish with `grin-wallet` without the CLI. When you run `./grin-wallet owner_api --run_foreign` before `./grin-wallet init` you receive this error.

    Wallet configuration not found at /home/gringineer/.grin/main.
    (Run `grin-wallet init` to create a new wallet

### Solution

Make running `./grin-wallet --password={{base64}}` the equivalent of 
```
./grin-wallet init --password={{base64}} && ./grin-wallet owner_api --run_foreign
```

**Comment by phyro** [comment]
Thanks for sharing your thoughts. My understanding is that the `--password` flag is specifically for the `init` subcommand. If this is the case, I personally don't believe we should be introducing such a shortcut because it's not really unintuitive

**Comment by gringineer** [comment]
You're not aiming high enough.

> it's not really unintuitive

'good enough' intuition has no place in software that is so unintuitive that you can't get developers to join your community.

**Comment by yeastplume** [comment]
We explicitly disallow providing passwords as arguments from the command line to avoid them being stored in shell history. Please feel free to reopen with justification as specified in the 'Feature Request' template.
