### ISSUE TITLE
slate serialization compatibility to 1.0.x

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin-wallet#6]
wallet send to 1.0.x wallet fail, and the error log on 1.0.x wallet:
```
Generic error: Invalid request body: invalid type: string "e1c141a8fce73ca7e8c546a865ba26ae1879259ab366fc54fd502bf0c04dc5fa", expected an array of length 32 at line 1 column 147 }
```

Looks like we didn't successfully compatible with 1.0.x slate serialization, but I remember we did.
To be checked...

**Comment by garyyu** [comment]
Related PR: https://github.com/mimblewimble/grin/pull/2534

**Comment by yeastplume** [comment]
I don't think there's actually code in there at the moment to produce and send the slate in v0 format. The slate versioning and conversion capability is there, but there's nothing that actually calls it.

**Comment by garyyu** [comment]
Okay, so this is still a todo item for us before the formal release of this wallet :-)

**Comment by mcdallas** [comment]
@garyyu This is working as intended, after 1.1.0 you won't be able to receive a tx from an old wallet if it was sent by a new wallet, only the other way around because the slate format changed to hex.

**Comment by garyyu** [comment]
@mcdallas 
> This is working as intended

**Why we intend to have an incompatible with old version?**

But If this is a method to force upgrading, I fully agree 😄   because of https://www.grin-forum.org/t/critical-vulnerability-in-grin-1-0-1-and-older-fixed-in-1-0-2/4343

And the release note of `1.1.0` must highlight this incompatible and the purpose.

**Comment by mcdallas** [comment]
Because how can the old client understand the new slate format? I don't think it's possible. I raised the issue of backwards incompatibility in the dev meeting and people seemed fine with it.

**Comment by yeastplume** [comment]
Just thinking about the work involved in maintaining compatibility between all wallet versions.

Say there are 4 versions of the slate, v1, v2, v3 and v4.

If you're on V4, you can "upgrade" all incoming messages from v1, v2 and v3 clients. However, to respond to them you also need to be able to downgrade to their message format, so I need to maintain code to upgrade from v1 -> v2 -> v3 -> v4 as well as to downgrade v4 -> v3 -> v2 -> v1. This will have to be an incremental process, so in adding v5 I need to add upgrade v4 -> v5 and downgrade v5 ->v4 and continue down the chain depending on who I'm talking to. So for each element in each version of the slate there are From<> implementations that upgrade to the next and downgrade to the previous.

Of course, that doesn't cover when new fields driving new functionality appear, these will probably need to be handled on a case-by-case basis.

**Comment by jaspervdm** [comment]
Maybe we can deprecate old slate versions at the hard fork moments, as they require users to upgrade their software anyway?

**Comment by kargakis** [comment]
> If you're on V4, you can "upgrade" all incoming messages from v1, v2 and v3 clients. However, to respond to them you also need to be able to downgrade to their message format, so I need to maintain code to upgrade from v1 -> v2 -> v3 -> v4 as well as to downgrade v4 -> v3 -> v2 -> v1. This will have to be an incremental process, so in adding v5 I need to add upgrade v4 -> v5 and downgrade v5 ->v4 and continue down the chain depending on who I'm talking to. So for each element in each version of the slate there are From<> implementations that upgrade to the next and downgrade to the previous.

I am not familiar with how much of the wallet code needs to be rewritten every time a new slate version is created but another approach you could take here is to maintain an intermediate "internal" format from which you can convert in and out with every external version. So you would have internal <-> v1, internal <-> v2, internal <-> v3, internal <-> v4.

**Comment by yeastplume** [comment]
@kargakis that means adding n_slate_versions conversions each time a slate is added. The way it's implemented now just requires 1 conversion implementation for each new slate version.

This is handled now, closing.

**Comment by kargakis** [comment]
> @kargakis that means adding n_slate_versions conversions each time a slate is added.

FWIW, this is not the case. You would only need to add conversions between the newest version N and the internal. Then to convert between two external versions N and N-X, you would have to go through the internal which supports conversions to both N and N-X.
