### ISSUE TITLE
How to transfer Grin to bittrex?

### ISSUE THREAD

**Issue by Chambers-Chambers** [mimblewimble/grin-wallet#609]
I remember a long time ago i mined a bunch of
 grin as well at btcz... i have grin downloaded;  and i found my encrypted seed but it is not the seed for my recovery password. Im unsure what to do with the encrypted seed or how to correctly place it into the recovery phrase bar  if it is encrypted, Im looking to open my wallet and transfer grin to bittrex.... any info is appreciated.

**Comment by deevope** [comment]
@Chambers-Chambers I'm not sure to understand, do you know the password of the encrypted seed? 
- If yes put your `wallet.seed` in this directory '~/.grin/main/wallet_data` (if there's already a wallet.seed back it up somewhere and delete it)
- if not, I think you can't access to this wallet, you must know the password, alternatively you can try to bruteforce it if the password was not long...

**Comment by Chambers-Chambers** [comment]
when i open wallet.seed it pulls up 3 words, i replaced stuff with "****" to hide whatever im needing.... there are not 12 of these
{
  "encrypted_seed": "**************************************************************************************************",
  "****": "****************",
  "*****": "****************"
}

**Comment by deevope** [comment]
@Chambers-Chambers As I said this file needs be decrypted. What you are seeing in this file is some element (nonce and salt) along with your wallet password that will help you to get the string 'encrypted_seed' to be decrypted. The only thing you need and it's still unclear to me : **Do you remember/have your password that was associated with this wallet file?**

- If yes put your wallet.seed in this directory ~/.grin/main/wallet_data (if there's already a wallet.seed back it up somewhere and delete it), then open the `grin-wallet info` and enter the password you remembered.
- if not, I think you can't access to this wallet, you must know the password, alternatively you can try to bruteforce it if the password was not long...

- If yes put your wallet.seed in this directory ~/.grin/main/wallet_data (if there's already a wallet.seed back it up somewhere and delete it)
- if not, I think you can't access to this wallet, you must know the password, alternatively you can try to bruteforce it if the password was not long...

**Comment by Chambers-Chambers** [comment]
i thought i had stored it in the same file at the grin wallet but im unsure how i would locate it. I have written down every other pass word on paper but grin, not sure how one would find a random file for grin password in the pc.
your saying those 2 elements (nonce and salt) will help get the encrypted seed to be decrypted... but where does this get typed into?
im unsure of the password associated with the wallet but i assume i used one of my previous passowords used around the time of mining.... 

 i open grin-client-exe, 
 4 (enter)
tried every password and cant get in

**Comment by deevope** [comment]
@Chambers-Chambers 

> your saying those 2 elements (nonce and salt) will help get the encrypted seed to be decrypted... but where does this get typed into?

They don't need to, it's done automatically by the wallet. The only thing you need is your password.

> im unsure of the password associated with the wallet but i assume i used one of my previous passowords used around the time of mining....

Continue to try, there's no other solution.
