### ISSUE TITLE
Add --password-file option to the grin wallet command

### ISSUE THREAD

**Issue by Onefox** [mimblewimble/grin-wallet#61]
The problem is if you want to start off wallet listen and owner_apis you have to input your wallet password or use the flag -p.
The problem with -p is that your password will be there in plaintext within bash history or ps ux.

A solution would be to support file passwords.
That way the service can be started and the file with the password deleted after the successful start.

Monero has this option and it works very well there.

**Comment by yeastplume** [comment]
Think solution provided is adequate
