### ISSUE TITLE
Unable to send GRIN via file

### ISSUE THREAD

**Issue by shuan9-polo** [mimblewimble/grin-wallet#614]
**Describe the bug**
Unable to use the cli commands `grin-wallet send -m file -d my_grin_transaction.tx 1` to create a transaction file. The returned errors are as below:
```console
# grin-wallet send -m file -d my_grin_transaction.tx 1
error: Found argument '1' which wasn't expected, or isn't valid in this context

USAGE:
    grin-wallet send --dest <dest> --manual

For more information try --help
```

**To Reproduce**
1. run the commands `grin-wallet send -m file -d my_grin_transaction.tx 1`
2. The reported errors will be returned

**Expected behavior**
A transaction file should be created as described in https://github.com/mimblewimble/docs/wiki/How-to-use-the-Grin-wallet#create-a-transaction-file.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Version: grin-wallet 5.0.3

**Additional context**
N/A

**Comment by phyro** [comment]
@shuan9-polo thank you for filing this. We'll take a look at what's happening

**Comment by phyro** [comment]
@shuan9-polo sorry, the wiki seems to be out of date. Please refer to https://docs.grin.mw/getting-started/wallet-handbook/#send
I also suggest you check your available options with `grin-wallet send --help` and check if `--manual` or `-u` work for you.

**Comment by shuan9-polo** [comment]
Hi @phyro , thanks for checking my request and sharing the link https://docs.grin.mw/getting-started/wallet-handbook/#send.

What I need to do is to deposit some GRINIs into my Bittrex account, but Bittrex only supports the deposit via file - https://bittrexglobal.zendesk.com/hc/en-us/articles/360009688199.

As I understand from the instructions of `send` command,
* `-m` should be specified for "send" via file instead of TOR network
* `-d` needs to be ignored as Bittrex does not provide any address info
* `-u` should be specified to save the unencrypted slatepack messages into a output file instead of printing the messages out

So in general, my steps of depositing GRINs into Bittrex account is:
1. I should use commands `grin-wallet send -m -u my_grin_transaction.tx 1` to generate the output file keeping the slatepack messages
2. On Bittrex, upload the `my_grin_transaction.tx` to their service so as to achieve something similar to running commands `grin-wallet receive -i $PATH/my_grin_transaction.tx`
3. Once 2 is completed, I should use commands `grin-wallet finalize` to complete the slatepack transaction

Could you please confirm if my understanding is correct?

One thing I am also concerned about is if the `my_grin_transaction.tx` mentioned in the outdated doc https://github.com/mimblewimble/docs/wiki/How-to-use-the-Grin-wallet#create-a-transaction-file is equivalent to the output file generated by commands `grin-wallet send -m -u my_grin_transaction.tx 1`. Could you please also shed some light on this?

Appreciate your help!

**Comment by phyro** [comment]
@shuan9-polo Grin introduced a new standard for building transactions called Slatepack and it seems like Bittrex didn't upgrade to support Slatepack. The `file` method they mention has been removed. I'm honestly not sure whether you can use the new Slatepack method if they expect the old format. Perhaps it's worth trying the steps you wrote to see if they will in fact accept a file in this new format, but I wouldn't bet on it working. Sorry for the inconvenience, we hope the situation with exchange integration improves in the future.

**Comment by shuan9-polo** [comment]
Sorry for the late update. The Bittrex does not support the "new" txs file. I am going to close this issue. Thanks for helping!
