### ISSUE TITLE
can not get refreshed balance with /v1/wallet/owner/retrieve_summary_info?refresh

### ISSUE THREAD

**Issue by past2017** [mimblewimble/grin-wallet#63]
**Describe the bug**
By /v1/wallet/owner/retrieve_summary_info?refresh I can get wallet grin balance, but this balance is not refreshed, it is not latest
After run 'grin wallet check" and then run  /v1/wallet/owner/retrieve_summary_info?refresh, then will get correct balance

Please tell me how to get the refreshed and latest grin balance by API

**Comment by yeastplume** [comment]
closing for lack of detail
