### ISSUE TITLE
Request error: Cannot make request: parsed HTTP message from remote is incomplete

### ISSUE THREAD

**Issue by superphly** [mimblewimble/grin-wallet#65]
**Describe the bug**
After using `grin` and `grin wallet check` and doing some successful transfers, I'm unable to check my balance now with `grin wallet check`. I'm getting this error:

20190201 15:13:31.976 ERROR grin_wallet::node_clients::http - get_outputs_by_pmmr_index: unable to contact API http://127.0.0.1:3413. Error: Request error: Cannot make request: parsed HTTP message from remote is incomplete

**To Reproduce**
1. Run 'grin wallet check'
2. Expect data on my balance

**Comment by yeastplume** [comment]
This is from a very early version and should most likely be fine now. Please reopen if not the case in v2.0.0
