### ISSUE TITLE
API wallet/owner/retrieve_outputs doesn't return mmr_index of the outputs

### ISSUE THREAD

**Issue by Onefox** [mimblewimble/grin-wallet#68]
Since a output commitment is only unique in the current UTXO set the wallet API should also provide correct mmr_indexs of all outputs to distinguish between outputs.

1. Call [retrieve_outputs](https://github.com/mimblewimble/grin/blob/master/doc/api/wallet_owner_api.md#get-retrieve-outputs) on a Unspent output
2. Expect the output to have a mmr_index
3. The mmr_index is always null

version v1.0.1

The mmr_index is also not given via the cli command txs -i X

**Comment by yeastplume** [comment]
Newly created outputs don't have an MMR index, it's only populated when an output is retrieved from the chain as in a `restore` or `check` command. This is to prevent duplicate commits under certain conditions.

This is a time intensive operation, so we won't be retrieving the MMR index for every output any time soon. Wallet creators shouldn't be building functionality that assumes the MMR index is populated
