### ISSUE TITLE
Transaction state doesn't match between sender and recipient

### ISSUE THREAD

**Issue by alesito85** [mimblewimble/grin-wallet#69]
I've previously opened issue #2318 but this has happened again. I'm running version 1.0.0 and the sender has transaction marked as confirmed=false, while recipient has confirmed=true. When I run check nothing changes. How to proceed with this?

**Comment by alesito85** [comment]
Has this issue been resolved or just closed?

**Comment by bladedoyle** [comment]
Just closed I guess.   Bug is still being seen in new grin-wallet project version 1.1.0 issue #135 (linked above)
