### ISSUE TITLE
Provable Interactive Transaction

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin-wallet#75]
RECENT CHANGES:
- (6 Mar 2019) Combine the pubkey and destination fields, according to @jaspervdm 's comment.
- (5 Mar 2019) Creation.

## Table of Contents  
- [Use case](#usecase)
  - [In Bitcoin](#inbitcoin)
  - [In Grin](#ingrin)
- [Provable Interactive Transaction solution](#pits) 
  - [Recap of Grin current slate structure in the Interactive Transaction](#recap)
  - [Enhance Grin transaction as a provable transaction](#enhance)
    - [Wallet URL with the receiver's "address"](#walleturl)
    - [Step 1: Alice send Bob a slate](#step1)
    - [Step 2: Bob receive above slate and send back the processed slate to Alice](#step2)
    - [Step 3: Alice receive above slate and generate a finalized slate](#step3)
    - [Finish](#finish)
  - [Alice prove she did this transaction](#prove)
- [Grin "address" generation](#grinaddr)
- [Other use cases](#other)
- [Validation API](#api)

<a name="usecase"/>

# 1. Use case

<a name="inbitcoin"/>

## 1.1 In Bitcoin

In the Bitcoin transaction scenario, Bob tell Alice his Bitcoin address, for example: [3ChVP627...](https://www.blockchain.com/btc/address/3ChVP627KU5w4zu2rieFPF3wGXWQgmhvrs), and Alice do a Bitcoin transaction to pay to this address, for example: [3169d1b5...](https://www.blockchain.com/btc/tx/3169d1b575955648694da900d3f8d6aed34e65cdcf79f3ed16e6996788fda714), and the ***HASH160*** form of this address is directly put on the public chain database (as the Output Scripts): ```HASH160 PUSHDATA(20)[78c04dda49b06260020a106f8e279b1bfbadcb71] EQUAL```. 

This is a perfect **provable** transaction, since there's no way for Bob to deny he received this payment.

<a name="ingrin"/>

## 1.2 In Grin

In the Grin transaction scenario, Bob tell Alice his Grin wallet address, for example: `https://bob.grinwallet.me:3415`, and Alice do a Grin transaction to pay to Bob's said wallet. Once the transaction is done and confirmed on the chain, Bob has his UTXO on the chain, for example: [0861105a...](https://grinscan.net/output/0861105a99353111dc62f01708ed5b31d68ec6d6a9cebc2a46491821525883e4e3).

But the practical problem is: there's no any public indicator on the chain which can prove this output belongs to Bob. ONLY Bob can prove this output belongs to himself, nobody else without Bob's private key!

So, in case Bob **deny** he received Alice's payment, it will be very complex for Alice to prove she paid, and even impossible if she can't force Bob to provide related evidence.

<a name="pits"/>

# 2. Provable Interactive Transaction solution

<a name="recap"/>
## 2.1 Recap of Grin current slate structure in the Interactive Transaction

Let's take a look at an example of a finalized slate (of a wallet transaction):
```Javascript
{
  "num_participants": 2,
  "id": "8ba033b6-3e05-4cad-81ec-937f3056b1e8",
  "tx": {
    "offset": [...],
    "body": {
      "inputs": [
        {
          "features": "Plain",
          "commit": [...],
        }
      ],
      "outputs": [
        {
          "features": "Plain",
          "commit": [...],
          "proof": [...],
        },
        {
          "features": "Plain",
          "commit": [...],
          "proof": [...],
       }
      ],
      "kernels": [
        {
          "features": "HeightLocked",
          "fee": 8000000,
          "lock_height": 18187,
          "excess": [...],
          "excess_sig": [...],
       }
      ]
    }
  },
  "amount": 110000000,
  "fee": 8000000,
  "height": 18187,
  "lock_height": 18187,
  "participant_data": [
    {
      "id": 0,
      "public_blind_excess": [...],
      "public_nonce": [...],
      "part_sig": [...],
      "message": null,
      "message_sig": null
    },
    {
      "id": 1,
      "public_blind_excess": [...],
      "public_nonce": [...],
      "part_sig": [...],
      "message": null,
      "message_sig": null
     }
  ]
}
```
For the detail meaning of this structure, please refer to https://github.com/mimblewimble/grin/blob/391e311f4c05619bd4b7b0d599a5071ce7753b90/wallet/src/libwallet/slate.rs#L104:L127

<a name="enhance"/>

## 2.2 Enhance Grin transaction as a provable transaction

The basic idea is to import the exact same **"address"** concept as Bitcoin, but only use it on the Grin transaction, not on the chain.

Still with above example slate, but with the enhanced fields:
```diff
{
  "num_participants": 2,
  "id": "8ba033b6-3e05-4cad-81ec-937f3056b1e8",
  "tx": {
    "offset": [...],
    "body": {
    (exact same as the original format)
    }
  },
  "amount": 110000000,
  "fee": 8000000,
  "height": 18187,
  "lock_height": 18187,
  "participant_data": [
    {
      "id": 0,
      "public_blind_excess": [...],
      "public_nonce": [...],
      "part_sig": [...],
      "message": null,
      "message_sig": null,
+     "p2pkh_dest": null,
+     "p2pkh_public_key": null,
+     "p2pkh_msg": [...],
+     "p2pkh_sig": [...]
    },
    {
      "id": 1,
      "public_blind_excess": [...],
      "public_nonce": [...],
      "part_sig": [...],
      "message": null,
      "message_sig": null,
+      "p2pkh_dest": [https://addr@hostname:port],
+      "p2pkh_public_key": [...],
+      "p2pkh_msg": [...],
+      "p2pkh_sig": [...]
     }
  ]
}
```

**Note**: `p2pkh_dest` can be `https://addr@hostname:port`, or `keybase://addr@username`, or other transport method/s.

Here is the proposal for this provable Grin transaction procedure.

<a name="walleturl"/>

### 2.2.1 Wallet URL with the receiver's "address"

For example, when Bob tell Alice his Grin wallet address, he give both his wallet URL and his "address": `https://3ChVP627KU5w4zu2rieFPF3wGXWQgmhvrs@bob.grinwallet.me:3415`.

This "address" has exact same format as Bitcoin's legacy address.

<a name="step1"/>

### 2.2.2 Step 1: Alice send Bob a slate

```diff
{
  "num_participants": 2,
  "id": "8ba033b6-3e05-4cad-81ec-937f3056b1e8",
  "tx": {
    "offset": [...],
    "body": {
    (exact same as the original format and content)
    }
  },
  "amount": 110000000,
  "fee": 8000000,
  "height": 18187,
  "lock_height": 18187,
  "participant_data": [
    {
      "id": 0,
      "public_blind_excess": [...],
      "public_nonce": [...],
      "part_sig":  null,
      "message": null,
      "message_sig": null,
+     "p2pkh_dest": null,
+     "p2pkh_public_key": null,
+     "p2pkh_msg": [...],
+     "p2pkh_sig": [...]
    }
  ]
}
```
As the sender / payer, Alice:
- leave `p2pkh_public_key` and `p2pkh_dest` as `null`
- put the `p2pkh_msg` as the HASH of this slate data (exclude  `p2pkh_*` and all other `participant_data` array elements, and exclude `id`)
- and put `p2pkh_sig` as the signature of this `p2pkh_msg` with the private key related to `public_blind_excess`. 

**Note**: Alice must keep the told Bob's `p2pkh_dest` at somewhere, and need to use them in the 3rd step.

<a name="step2"/>

### 2.2.3 Step 2: Bob receive above slate and send back the processed slate to Alice

**Note**: for security, Bob need check the received payment request whether his own "address" is there. If no, giving warning at this moment for compatibility of old version, and in the future we close the connection or ban the sender's IP in this case.

```diff
{
  "num_participants": 2,
  "id": "8ba033b6-3e05-4cad-81ec-937f3056b1e8",
  "tx": {
    "offset": [...],
    "body": {
    (exact same as the original format and content)
    }
  },
  "amount": 110000000,
  "fee": 8000000,
  "height": 18187,
  "lock_height": 18187,
  "participant_data": [
    {
      "id": 0,
      (same data as above received slate)
    },
    {
      "id": 1,
      "public_blind_excess": [...],
      "public_nonce": [...],
      "part_sig": [...],
      "message": null,
      "message_sig": null,
+      "p2pkh_dest": [3ChVP627KU5w4zu2rieFPF3wGXWQgmhvrs@https://bob.grinwallet.me:3415],
+      "p2pkh_public_key": [...],
+      "p2pkh_msg": [...],
+      "p2pkh_sig": [...]
     }
  ]
}
```
As the receiver / payee, Bob: 
- **must** put the correct `p2pkh_dest` which must be exact same as what he told Alice for this payment, and `address` as the 1st part of this `p2pkh_dest`
- put `p2pkh_public_key` as the one which match the `address`
- put the `p2pkh_msg` as the HASH of this slate data (exclude  `p2pkh_*` and all other `participant_data` array elements, and exclude `id`)
- and put `p2pkh_sig` as the signature of this `p2pkh_msg` with the private key related to `p2pkh_public_key`. 

<a name="step3"/>

### 2.2.4 Step 3: Alice receive above slate and generate a finalized slate

```diff
{
  "num_participants": 2,
  "id": "8ba033b6-3e05-4cad-81ec-937f3056b1e8",
  "tx": {
    "offset": [...],
    "body": {
    (exact same as the original format and content)
    }
  },
  "amount": 110000000,
  "fee": 8000000,
  "height": 18187,
  "lock_height": 18187,
  "participant_data": [
    {
      "id": 0,
      "public_blind_excess": [...],
      "public_nonce": [...],
+     "part_sig": [...],
      "message": null,
      "message_sig": null,
      "p2pkh_dest": null,
      "p2pkh_public_key": null,
+     "p2pkh_msg": [...],
+     "p2pkh_sig": [...]
    },
    {
      "id": 1,
      (same data as above received slate)
     }
  ]
}
```

As the sender / payer, Alice: 
- **must** check the above received slate for the `p2pkh_dest`, which must be exact same as what she was told by Bob for this payment
- **must** check the `address` is indeed generated by `p2pkh_public_key`
- create her own partial signature for this transaction and update the `tx body`
- update her `p2pkh_msg` and `p2pkh_sig`
- keep this finalized slate stored at her wallet database, for any possible "provable" request in the future.

<a name="finish"/>

### 2.2.5 Finish

Alice post this transaction to the chain and this transaction will be confirmed at a few minutes.

<a name="prove"/>

## 2.3 Alice prove she did this transaction

For example, Bob deny and say he never receive this transaction from Alice.

Alice show / publish her saved finalized slate for this transaction, to Bob or any other 3rd party, anyone can validate this data and confirm Bob's lying, since this slate include Bob's address and Bob's signature, and the integrity checking.

<a name="grinaddr"/>

# 3.Grin "address" generation

Since we already have BIP-32 HD wallet feature, it should be an easy point to have this / these "address"/es.

Btw, to support the new "address"/es, Grin wallet need to store all published / used "address", to enable the checking of any receiving payment requests, either on current "address" or on any previous "address".

<a name="other"/>

# 4.Other use cases

I'm thinking it seems possible to share the wallet database with the auditor/s, without telling the wallet seed / private key. The auditor/s still can get the logs which can be easily validated. To be discussed with a separated issue / topic.

<a name="api"/>

# 5.Validation API

We need some new API to enable an easy validation on this "provable" slate.

**Welcome your review and any comments :-)**
**Especially for the security level with this solution. Please feel free to correct me if any mistakes**

**Comment by yeastplume** [comment]
I believe this has been covered by recent payment proofs discussion and work, so going to close this thread.
