### ISSUE TITLE
Read Only Wallet Database User and Read Only Wallet API

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin-wallet#76]
**Is your feature request related to a problem? Please describe.**
Currently, there's no solution for an auditor to read the wallet transaction log without giving the wallet password, or no solution for wallet API to have a read only right (no access for `issue_send_tx` for example).

**Describe the solution you'd like**
To be discussed.

**Comment by yeastplume** [comment]
Please feel free to open again if you have a specific proposal, right now it seems to me 'can't access the wallet data without a password' which seems correct to me. If someone wants to show someone the transaction log, they can dump it and send it manually.
