### ISSUE TITLE
Non-interactive transactions seem lower-friction than interactive ones

### ISSUE THREAD

**Issue by Arvanaghi** [mimblewimble/grin-wallet#77]
**Is your feature request related to a problem? Please describe.**
Non-interactive transactions (e.g. Alice -> Bob) seem both plausible and lower-friction than the current `Alice -> Bob -> Alice` workflow.

**Describe the solution you'd like**
Alice wants to send to Bob, so instead of getting commitments from Bob, she creates her change output for herself and also picks all the private values Bob would have picked for his output. She completes the transaction.

Then, at some point in the future, Alice sends Bob all the secrets she chose for him, along with the output. Bob runs:

`grin take-ownership <File containing the secrets Alice chose for Bob>`
...which automatically creates a Grin transaction from the output Alice made for Bob to a new output that only Bob controls.

So two total transactions, but one less interaction needed between Alice and Bob. And, these two transactions would automatically condense on-chain, because they model an `Alice -> Bob -> Charlie` chain.

**Describe alternatives you've considered**
N/A

**Additional context**
The trust relationship in the existing Grin transaction model is exactly the same as in the one I am proposing. In my view, this proposal is strictly an optimization. Let's examine.

In my proposal, the risks are:
1) Bob can try and take-ownership of the transaction, and see that the transaction has already been spent.
2) Bob can try and take-ownership of the transaction, and see that the amount is not what he had hoped.
3) Bob can try and take-ownership of the transaction, successfully collect the Grin, and claim he never received it.

All of these risks are present in the existing Alice -> Bob -> Alice interactive model. Why? Because everything relies on Alice anyway.

After receiving Bob's partial signature, Alice is the one who needs add her signature, and then broadcast the transaction. Bob can't!

Knowing this, the risks of the existing model are:
1) Alice could never broadcast the transaction. At best, Bob can say "you didn't send me Grin!" and Alice could say "yes I did!". In a dispute like this, there is literally no way that Alice could prove she sent the Grin to Bob.
--> Similarly, in my proposal, Bob could say "the blinding factor and output you sent me -- you already spent it!" and Alice could say "no I didn't!"
2) Bob could successfully receive the Grin, yet still tell Alice "you didn't send that Grin to me -- you sent it to someone else/a blinding factor you control!"
--> The same risk is present in my proposal.

**Comment by yeastplume** [comment]
Closing, as I don't think any particular actions will come from this issue. (Always open to further specific proposals, of course)
