### ISSUE TITLE
wallet builds invalid URL

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin-wallet#80]
**Describe the bug**
It looks like the wallet is building the url incorrectly when sending grin to http[s] address.  For the case where URL arguments are provided (poloniex) the ```/v1/wallet/foreign/receive_tx``` part of the url is being appended to the end of the argument list.

I guess poloniex attempted to "work around" this, but as a result the order of the arguments matters (which they should not).

**To Reproduce**
Attempt to send grin to poloniex with the URL arguments in a different order - ie, dont put the "id" argument last.

**Screenshots**
This works (id argument last):
```
20190321 18:20:58.846 INFO grin_wallet::command - Tx created: 1.000000000 grin to https://poloniex.com/public?currency=GRIN&command=createDeposit&id=8161xxxx-73xx-47xx-b9xx-f66e2cexxxxx (strategy 'all')
20190321 18:20:58.847 DEBUG grin_wallet::adapters::http - Posting transaction slate to https://poloniex.com/public?currency=GRIN&command=createDeposit&id=8161xxxx-73xx-47xx-b9xx-f66e2cexxxxx/v1/wallet/foreign/receive_tx
```

This does not work (id argument not last):
```
20190321 18:20:07.795 INFO grin_wallet::command - Tx created: 1.000000000 grin to https://poloniex.com/public?command=createDeposit&id=8161xxxx-73xx-47xx-b9xx-f66e2cexxxxx&currency=GRIN (strategy 'all')
20190321 18:20:07.795 DEBUG grin_wallet::adapters::http - Posting transaction slate to https://poloniex.com/public?command=createDeposit&id=8161xxxx-73xx-47xx-b9xx-f66e2cexxxxx&currency=GRIN/v1/wallet/foreign/receive_tx
```

**Comment by yeastplume** [comment]
Indeed, V2 api is post-only and goes to a single endpoint, shouldn't be an issue in future.
