### ISSUE TITLE
Feature request: Offline send

### ISSUE THREAD

**Issue by casey** [mimblewimble/grin-wallet#82]
I'd like to be able to send transactions from a machine without network access, however this doesn't seem to be currently supported. Correct me if I'm wrong, but the `finalize` command expects to be able to broadcast the finalized transaction immediately, so if the sending wallet is offline, it won't be able to complete the `send`, `receive`, `finalize` sequence.

I think this is valuable for security, since it allows sending funds from secure machine that isn't connected to the internet.

The simplest implementation would be to add an option to `finalize` to dump the final transaction, which could then be moved to an online machine for broadcast. Or, if #2473 allowed an online-invoice, offline-send, online-finalize flow, that would work too, and would potentially mean one less transfer between machines. (As opposed to an offline-send, online-receive, offline-finalize-dump, online-broadcast flow.)

**Comment by yeastplume** [comment]
This functionality is in place now via https://github.com/mimblewimble/grin-wallet/pull/255
