### ISSUE TITLE
V2 API Slate Conversion

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin-wallet#84]
The V2 JSON-RPC API is working very well for most purposes, however the current construction is likely to have some issues with slate versioning.

In the V1 API, when a slate is passed in to any of the functions, there is a conversion process that interprets the entire slate as a raw string, checks the version number, upgrades it to the most recent (or internal) slate version, then deserializes. When sending the slate back, there is another process that downgrades the slate back to the version that was sent, then sends it back.

In V2, easy-jsonrpc handles all of API generation, but wherever a slate appears as a parameter or return value it can only be de/serialised as the most recent version. 

As an example, say I have 2 wallets, one with the most recent slate (S2), and one that's a version behind (S1). S2 has a new required field in the slate `new_data`. S1 wallet sends a slate to the `recieve_tx`function of the S2 wallet, that doesn't contain this field, and a serialization error occurs. If I make the new field optional instead, the incoming serialisation will be fine, but I have no way to downgrade the slate back to the previous version, and S1 will get a slate with an unexpected field in it.

@bddap Is there any sane way to provide some kind of hook in easy-jsonrpc to allow this?

**Comment by bddap** [comment]
My understading of problem: we want to accept any previous slate format, and always return the slate
in the same format. We also want the option to add new formats in the future.

After some consideration, I don't know of any tweaks we could make to easy-jsonrpc to solve the
problem, but here are couple other solutions.

## Option 1.

Create a newtype with [untagged ser/de](https://serde.rs/enum-representations.html#untagged)

```rust
#[derive(Serialize, Deserialize)]
#[serde(untagged)]
// Versions are ordered newest to oldest so serde attempts to
// deserialize newer versions first, then falls back to older versions.
pub enum VersionedSlate {
    V2(SlateV2),
    V1(SlateV1),
    V0(SlateV0),
}

impl VersionedSlate {
    pub fn version(&self) -> SlateVersion { ... }
    /// convert this slate type to a the specified, potentially older version
    pub fn into_version(slate: Slate, version: SlateVersion) -> VersionedSlate { ... }
}

impl From<VersionedSlate> for Slate { ... }

pub enum SlateVersion {
    V0,
    V1,
    V2,
}

// and in the implementations of ForeignRpc

fn receive_tx(
    &self,
    slate: VersionedSlate,
    dest_acct_name: Option<String>,
    message: Option<String>,
) -> Result<VersionedSlate, ErrorKind> {
    let version = slate.version();
    let mut slate: Slate = slate.into();
    
    /// recieve tx
    
    Ok(VersionedSlate::into_version(slate, version))
}
```

The [current deserialization process](https://github.com/mimblewimble/grin-wallet/blob/0e9ccef3e5b2ce4217b9b52f3039beb4a1dd5b9f/libwallet/src/slate.rs#L168-L184) is sematically equivalet to serde's untagged enum deserialization. ser/de on VersionedSlate would be automatically generatated, we would keep the option to manually implement Deserialize later.

PRO: This api is explicit about the fact that multiple slate version are accepted.

CON: This api is not explicit about the fact that the (return format) == (receive format).
It also never comunicates to clients which versions the api supports.

## Option 2.

Be explicit about accepted slate formats in the rpc definitions. easy-jsonrpc allows default trait methods
so implementation would be trival.

```rust
/// inside ForeignRpc trait definition

// same as before
fn receive_tx(
    &self,
    slate: Slate,
    dest_acct_name: Option<String>,
    message: Option<String>,
) -> Result<Slate, ErrorKind>;

fn receive_tx_v0(
    &self,
    slate: SlateV0,
    dest_acct_name: Option<String>,
    message: Option<String>,
) -> Result<SlateV0, ErrorKind> {
    self.receive_tx(slate.into(), dest_acct_name, message).map(Into::onto)
}
```

**Comment by yeastplume** [comment]
Thank you, I think option 1 and `untagged` is precisely what we're looking for here. I wouldn't worry too much about not being explicit with the versioning, I'm also planning on implementing a call via which a wallet can return it's slate version + supported version. 

I'll try and put together an implementation of option 1, would appreciate if you could have a look at it later. Thanks again.

**Comment by yeastplume** [comment]
Addressed in PR
