### ISSUE TITLE
Cannot connect to a node on an external network

### ISSUE THREAD

**Issue by michaeldzjap** [mimblewimble/grin-wallet#92]
I have a Docker setup where the first container is running a Grin node (v1.1.0-beta.1) and the second container is meant to run a Grin wallet listener (v1.1.0-beta.1), but I am running into the two following issues:

1 - The container running the Grin node after about 5 / 10 minutes of running fine will error with the following snippet:

```
 20190425 19:31:53.014 ERROR grin_chain::txhashset::txhashset - hashset_replace fail on txhashset. err: Invalid cross-device link (os error 18)
grin-server_1  | 20190425 19:31:53.051 ERROR grin_servers::common::adapters - Failed to save txhashset archive: TxHashSetErr: txhashset replacing fail 
grin-server_1  |  Cause: Unknown 
grin-server_1  |  Backtrace: 
grin-server_1  | 20190425 19:31:53.053 ERROR grin_servers::grin::sync::state_sync - state_sync: error = Chain(Error { inner: 
grin-server_1  | 
grin-server_1  | TxHashSetErr: txhashset replacing fail }). restart fast sync
grin-server_1  | 20190425 19:33:21.552 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
grin-server_1  | 20190425 19:33:21.552 ERROR grin_chain::chain - txhashset_write: corrupted storage? oldest_height is 0 when check_txhashset_needed. state sync is needed
grin-server_1  | 20190425 19:35:20.787 ERROR grin_chain::txhashset::txhashset - hashset_replace fail on txhashset. err: Invalid cross-device link (os error 18)
grin-server_1  | 20190425 19:35:20.826 ERROR grin_servers::common::adapters - Failed to save txhashset archive: TxHashSetErr: txhashset replacing fail 
grin-server_1  |  Cause: Unknown 
grin-server_1  |  Backtrace: 
grin-server_1  | 20190425 19:35:20.830 ERROR grin_servers::grin::sync::state_sync - state_sync: error = Chain(Error { inner: 
grin-server_1  | 
grin-server_1  | TxHashSetErr: txhashset replacing fail }). restart fast sync
grin-server_1  | 20190425 19:36:05.917 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
grin-server_1  | 20190425 19:36:05.917 ERROR grin_chain::chain - txhashset_write: corrupted storage? oldest_height is 0 when check_txhashset_needed. state sync is needed
```

Now I am not sure if the above error is due to making a failing request (see point 2) or is related or identical to [this](https://github.com/mimblewimble/grin/issues/2770)

2 - I don't seem to be able to make a successful request (either before or after the error described in point 1) from the container running the wallet to the container running the node. For instance when trying the command:

```
grin-wallet --floonet -e -r "http://172.18.0.3:13413" -p secret info
```

or

```
grin-wallet --floonet -e -r "http://grin-server:13413" -p secret info
```

where 172.18.0.3 is the IP of the container running my Grin node and grin-server is the name of that container. This throws the error:

```
ERROR grin_wallet_impls::node_clients::http - Get chain height error: Request error: Cannot make request: an error occurred trying to connect: Connection refused (os error 111)
```

without saying much else. I can ping the container running the node from the container running the wallet without a problem. Both `ping -w 4 grin-server` as well as `ping -w 4 172.18.0.3` return a valid response. It also cannot be a difference in API secret, as I have made sure that both container use the same API secret (i.e. the content of the .api_secret file is exactly same). I cannot really think of anything else to be honest. Maybe I am doing something wrong, maybe it is an error. I hope someone can give some advice.

**Comment by kargakis** [comment]
Try rebuilding your grin node image with [this](https://github.com/mimblewimble/grin/pull/2753) fix.

**Comment by michaeldzjap** [comment]
@kargakis Thanks. That seems to have solved problem 1. The grin server / node is not crashing anymore. However, problem 2 still remains. Would you have any idea where I could start looking into debugging this myself perhaps? Also tried with leaving the protocol off it so:

```
grin-wallet --floonet -e -r "172.18.0.3:13413" -p secret info
```

But that doesn't seem to produce a valid URL:

```
ERROR grin_wallet_impls::node_clients::http - Get chain height error: Bad arguments: Invalid url 172.18.0.5:13413/v1/chain
```

**Comment by kargakis** [comment]
This might be an issue with ports - can you ensure you have 13413 open in the node container?

**Comment by michaeldzjap** [comment]
I'm pretty sure its open. `docker port CONTAINER_ID` for the container running the node returns:

```
13413/tcp -> 0.0.0.0:13413
13414/tcp -> 0.0.0.0:13414
```

**Comment by kargakis** [comment]
Are you able to reach the node from the wallet container using something like `curl`?

**Comment by michaeldzjap** [comment]
To be honest, I've only tried with the ping command and that seems to work fine. But the ping command cannot be used to ping a specific port of course. So I will try curl and report back.

**Comment by kargakis** [comment]
If your issue persists, it would be good to provide a reproducer so others can try to simulate your env (eg. how you run the containers, what images do you use, etc.)

**Comment by michaeldzjap** [comment]
Testing with curl fails as well actually. Seems to be a port issue indeed. I tried:

```
curl -v -0 -GET http://grin-server:13413/v1/wallet/owner/retrieve_summary_info?refresh\&minimum_confirmations=10
```

which returns:

```
*   Trying 172.18.0.5...
* TCP_NODELAY set
* connect to 172.18.0.5 port 13413 failed: Connection refused
* Failed to connect to grin-server port 13413: Connection refused
* Closing connection 0
curl: (7) Failed to connect to grin-server port 13413: Connection refused
```

I've attached my current Docker / Grin setup. I'm working on quite a big project where Grin is just one (but important) part of, so I have tried to isolate the attached files to only the relevant Grin related parts. @kargakis if you or someone else would want to have a look at it or try it out that would be greatly appreciated. Perhaps I am missing or misunderstanding something. To build:

```
docker-compose -f docker-compose.yml -f docker-compose.dev.yml build
```

and then run:

```
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
```

[test.zip](https://github.com/mimblewimble/grin-wallet/files/3122352/test.zip)

**Comment by kargakis** [comment]
I had a quick look at your config, you may want to add the following stanza in your server entrypoint and try again
```bash
sed -i -e 's/api_http_addr = "127.0.0.1:13413"/api_http_addr = "0.0.0.0:13413"/' $path/grin-server.toml
sed -i -e 's/api_http_addr = "127.0.0.1:3413"/api_http_addr = "0.0.0.0:3413"/' $path/grin-server.toml
```

**Comment by michaeldzjap** [comment]
> I had a quick look at your config, you may want to add the following stanza in your server entrypoint and try again
> 
> ```shell
> sed -i -e 's/api_http_addr = "127.0.0.1:13413"/api_http_addr = "0.0.0.0:13413"/' $path/grin-server.toml
> sed -i -e 's/api_http_addr = "127.0.0.1:3413"/api_http_addr = "0.0.0.0:3413"/' $path/grin-server.toml
> ```

Yes! That did the trick. Its working now. I totally overlooked that setting, but changing that makes sense obviously when the API needs to be reachable from a remote connection. Thanks for the help on this @kargakis. Will close the issue, as all seems solved.
