### ISSUE TITLE
Add /version API

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin-wallet#95]
Now we have these wallet APIs in `1.1.0` version:
- /v2/foreign/**
- /v2/owner/**
- /v1/wallet/foreign/**
- /v1/wallet/owner/**

How about add a `/version` API since `1.1.0` version?
1. We can use this `/version` API to make `1.1.0` version wallet sending to be compatible with `1.0.x` version receiving.  The `1.0.x` version will return `404 Not Found` for this API.
2. Sending side can detect the receiver's version in all the future versions since `1.1.0`.

**Comment by yeastplume** [comment]
This is already covered here: https://github.com/mimblewimble/grin-wallet/pull/87

I don't think we want to change the endpoint each time the api changes. V1 is the http api, V2 is the json-rpc api, but there is another version number within these that can be retrieved by the `check_version` function.

**Comment by garyyu** [comment]
Thanks.
Close this one since `check_version` works for that.

```
$ curl -0 -XPOST http://127.0.0.1:3415/v2/foreign --data '{"jsonrpc":"2.0","method":"check_version","id":1,"params":[]}'


{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "Ok": {
      "default_slate_version": 2,
      "foreign_api_version": 2
    }
  }
}
```
